In [1]:
import pandas as pd

from src.classification_utils import make_classification_tasks_with_known_answers

In [2]:
test_df = pd.read_csv('files/test_df.csv', index_col=("person_to_assign_id", "person_to_assign_family_id", "family_person_id", "family_id"))
test_df.head()

,,,,birthplace_distance,surname_distance,birthdate_distance,person_to_assign_name_other_person_middlename_distance,other_person_name_person_to_assign_middlename_distance,gender_male,other_person_gender_male,distance,sons_distance,daughters_distance,...,grandmothers_distance,grandfathers_distance,granddaughters_distance,grandsons_distance,nieces_distance,nephews_distance,aunts_distance,uncles_distance,kinship,assignment_task
person_to_assign_id,person_to_assign_family_id,family_person_id,family_id,,,,,,,,,,,,,,,,,,,,,
F0418_1,F0418,F0418_2,F0418,NaN,NaN,NaN,NaN,NaN,True,True,0.972775,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,child,"('F0418_1', 'F0418')"
F0098_7,F0098,F0418_2,F0418,NaN,NaN,NaN,NaN,NaN,False,True,0.992200,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F0418_1', 'F0418')"
F0875_4,F0875,F0418_2,F0418,NaN,NaN,NaN,NaN,NaN,True,True,1.007391,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F0418_1', 'F0418')"
F0293_4,F0293,F0418_2,F0418,NaN,NaN,NaN,NaN,NaN,False,True,0.904027,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F0418_1', 'F0418')"
F0272_4,F0272,F0418_2,F0418,NaN,NaN,NaN,NaN,NaN,False,True,1.096960,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F0418_1', 'F0418')"

In [3]:
from pickle import load


with open("files/FIW_rf_model.pkl", "rb") as pickle_file:
    rf = load(pickle_file)

In [4]:
X_test = test_df.drop(columns=['kinship', 'assignment_task'], axis=1)
y_test = test_df['kinship']

In [5]:
from sklearn.metrics import classification_report


preds = rf.predict(X_test)
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

       child       0.73      0.53      0.61       458
       other       0.97      0.99      0.98     23136
      parent       0.51      0.12      0.19       458
     sibling       0.69      0.58      0.63       428

    accuracy                           0.96     24480
   macro avg       0.73      0.55      0.60     24480
weighted avg       0.95      0.96      0.95     24480

In [6]:
test_proba = rf.predict_proba(X_test)

In [7]:
assignment_tasks_groups = test_df.groupby('assignment_task')

In [8]:
assignment_tasks_dfs = {}
for assignment_task, group in assignment_tasks_groups:
    assignment_tasks_dfs[assignment_task] = group
    print(assignment_task)

('F0021_1', 'F0021')
('F0021_2', 'F0021')
('F0021_3', 'F0021')
('F0021_4', 'F0021')
('F0023_1', 'F0023')
('F0023_2', 'F0023')
('F0023_3', 'F0023')
('F0023_4', 'F0023')
('F0023_5', 'F0023')
('F0023_6', 'F0023')
('F0033_1', 'F0033')
('F0033_2', 'F0033')
('F0033_3', 'F0033')
('F0033_4', 'F0033')
('F0033_5', 'F0033')
('F0033_6', 'F0033')
('F0043_1', 'F0043')
('F0043_2', 'F0043')
('F0043_3', 'F0043')
('F0043_4', 'F0043')
('F0054_1', 'F0054')
('F0054_2', 'F0054')
('F0054_3', 'F0054')
('F0054_4', 'F0054')
('F0080_1', 'F0080')
('F0080_2', 'F0080')
('F0080_3', 'F0080')
('F0080_4', 'F0080')
('F0080_5', 'F0080')
('F0080_6', 'F0080')
('F0080_7', 'F0080')
('F0080_8', 'F0080')
('F0089_1', 'F0089')
('F0089_2', 'F0089')
('F0089_3', 'F0089')
('F0090_1', 'F0090')
('F0090_10', 'F0090')
('F0090_11', 'F0090')
('F0090_12', 'F0090')
('F0090_13', 'F0090')
('F0090_14', 'F0090')
('F0090_15', 'F0090')
('F0090_16', 'F0090')
('F0090_2', 'F0090')
('F0090_3', 'F0090')
('F0090_4', 'F0090')
('F0090_5', 'F0090')
('F0090_6', 'F0090')
('F0090_7', 'F0090')
('F0090_8', 'F0090')
('F0090_9', 'F0090')
('F0097_1', 'F0097')
('F0097_2', 'F0097')
('F0097_3', 'F0097')
('F0097_4', 'F0097')
('F0097_5', 'F0097')
('F0098_1', 'F0098')
('F0098_2', 'F0098')
('F0098_3', 'F0098')
('F0098_4', 'F0098')
('F0098_5', 'F0098')
('F0098_6', 'F0098')
('F0098_7', 'F0098')
('F0117_1', 'F0117')
('F0117_2', 'F0117')
('F0117_3', 'F0117')
('F0117_4', 'F0117')
('F0117_5', 'F0117')
('F0118_1', 'F0118')
('F0118_2', 'F0118')
('F0118_3', 'F0118')
('F0118_4', 'F0118')
('F0118_5', 'F0118')
('F0118_6', 'F0118')
('F0118_7', 'F0118')
('F0144_1', 'F0144')
('F0144_2', 'F0144')
('F0144_3', 'F0144')
('F0144_4', 'F0144')
('F0144_5', 'F0144')
('F0144_6', 'F0144')
('F0144_7', 'F0144')
('F0144_8', 'F0144')
('F0166_1', 'F0166')
('F0166_2', 'F0166')
('F0166_3', 'F0166')
('F0166_4', 'F0166')
('F0181_1', 'F0181')
('F0181_2', 'F0181')
('F0181_3', 'F0181')
('F0181_4', 'F0181')
('F0181_5', 'F0181')
('F0216_1', 'F0216')
('F0216_2', 'F0216')
('F0216_3', 'F0216')
('F0216_4', 'F0216')
('F0216_5', 'F0216')
('F0216_6', 'F0216')
('F0216_7', 'F0216')
('F0229_1', 'F0229')
('F0229_2', 'F0229')
('F0229_3', 'F0229')
('F0229_4', 'F0229')
('F0229_5', 'F0229')
('F0229_6', 'F0229')
('F0251_1', 'F0251')
('F0251_2', 'F0251')
('F0251_3', 'F0251')
('F0251_4', 'F0251')
('F0251_5', 'F0251')
('F0251_6', 'F0251')
('F0251_7', 'F0251')
('F0251_8', 'F0251')
('F0251_9', 'F0251')
('F0252_1', 'F0252')
('F0252_2', 'F0252')
('F0252_3', 'F0252')
('F0252_4', 'F0252')
('F0252_5', 'F0252')
('F0254_1', 'F0254')
('F0254_2', 'F0254')
('F0254_3', 'F0254')
('F0254_4', 'F0254')
('F0254_5', 'F0254')
('F0254_6', 'F0254')
('F0256_1', 'F0256')
('F0256_2', 'F0256')
('F0256_3', 'F0256')
('F0256_4', 'F0256')
('F0256_5', 'F0256')
('F0256_6', 'F0256')
('F0256_7', 'F0256')
('F0264_1', 'F0264')
('F0264_10', 'F0264')
('F0264_2', 'F0264')
('F0264_3', 'F0264')
('F0264_4', 'F0264')
('F0264_5', 'F0264')
('F0264_6', 'F0264')
('F0264_7', 'F0264')
('F0264_8', 'F0264')
('F0264_9', 'F0264')
('F0272_1', 'F0272')
('F0272_2', 'F0272')
('F0272_3', 'F0272')
('F0272_4', 'F0272')
('F0272_5', 'F0272')
('F0273_1', 'F0273')
('F0273_2', 'F0273')
('F0273_3', 'F0273')
('F0273_4', 'F0273')
('F0293_1', 'F0293')
('F0293_10', 'F0293')
('F0293_2', 'F0293')
('F0293_3', 'F0293')
('F0293_4', 'F0293')
('F0293_5', 'F0293')
('F0293_6', 'F0293')
('F0293_7', 'F0293')
('F0293_8', 'F0293')
('F0293_9', 'F0293')
('F0300_1', 'F0300')
('F0300_2', 'F0300')
('F0300_3', 'F0300')
('F0300_4', 'F0300')
('F0315_1', 'F0315')
('F0315_2', 'F0315')
('F0315_3', 'F0315')
('F0315_4', 'F0315')
('F0322_1', 'F0322')
('F0322_2', 'F0322')
('F0322_3', 'F0322')
('F0355_1', 'F0355')
('F0355_2', 'F0355')
('F0355_3', 'F0355')
('F0355_4', 'F0355')
('F0373_1', 'F0373')
('F0373_2', 'F0373')
('F0373_3', 'F0373')
('F0373_4', 'F0373')
('F0380_1', 'F0380')
('F0380_2', 'F0380')
('F0380_3', 'F0380')
('F0380_4', 'F0380')
('F0380_5', 'F0380')
('F0380_6', 'F0380')
('F0380_7', 'F0380')
('F0387_1', 'F0387')
('F0387_2', 'F0387')
('F0387_3', 'F0387')
('F0387_4', 'F0387')
('F0387_5', 'F0387')
('F0387_6', 'F0387')
('F0387_7', 'F0387')
('F0391_1', 'F0391')
('F0391_2', 'F0391')
('F0391_3', 'F0391')
('F0391_4', 'F0391')
('F0393_1', 'F0393')
('F0393_2', 'F0393')
('F0393_3', 'F0393')
('F0393_4', 'F0393')
('F0393_5', 'F0393')
('F0393_6', 'F0393')
('F0395_1', 'F0395')
('F0395_2', 'F0395')
('F0395_3', 'F0395')
('F0402_1', 'F0402')
('F0402_2', 'F0402')
('F0402_3', 'F0402')
('F0402_4', 'F0402')
('F0402_5', 'F0402')
('F0402_6', 'F0402')
('F0402_7', 'F0402')
('F0402_8', 'F0402')
('F0415_1', 'F0415')
('F0415_2', 'F0415')
('F0415_3', 'F0415')
('F0418_1', 'F0418')
('F0418_2', 'F0418')
('F0418_3', 'F0418')
('F0425_1', 'F0425')
('F0425_10', 'F0425')
('F0425_2', 'F0425')
('F0425_3', 'F0425')
('F0425_4', 'F0425')
('F0425_5', 'F0425')
('F0425_6', 'F0425')
('F0425_7', 'F0425')
('F0425_8', 'F0425')
('F0425_9', 'F0425')
('F0439_1', 'F0439')
('F0439_2', 'F0439')
('F0439_3', 'F0439')
('F0439_4', 'F0439')
('F0439_5', 'F0439')
('F0439_6', 'F0439')
('F0439_7', 'F0439')
('F0439_8', 'F0439')
('F0439_9', 'F0439')
('F0453_1', 'F0453')
('F0453_2', 'F0453')
('F0453_3', 'F0453')
('F0453_4', 'F0453')
('F0454_1', 'F0454')
('F0454_2', 'F0454')
('F0454_3', 'F0454')
('F0478_1', 'F0478')
('F0478_2', 'F0478')
('F0478_3', 'F0478')
('F0478_4', 'F0478')
('F0478_5', 'F0478')
('F0478_6', 'F0478')
('F0478_7', 'F0478')
('F0525_1', 'F0525')
('F0525_2', 'F0525')
('F0525_3', 'F0525')
('F0525_4', 'F0525')
('F0528_1', 'F0528')
('F0528_2', 'F0528')
('F0528_3', 'F0528')
('F0528_4', 'F0528')
('F0528_5', 'F0528')
('F0528_6', 'F0528')
('F0539_1', 'F0539')
('F0539_2', 'F0539')
('F0539_3', 'F0539')
('F0539_4', 'F0539')
('F0549_1', 'F0549')
('F0549_2', 'F0549')
('F0549_3', 'F0549')
('F0549_4', 'F0549')
('F0565_1', 'F0565')
('F0565_2', 'F0565')
('F0565_3', 'F0565')
('F0565_4', 'F0565')
('F0571_1', 'F0571')
('F0571_2', 'F0571')
('F0571_3', 'F0571')
('F0583_1', 'F0583')
('F0583_2', 'F0583')
('F0583_3', 'F0583')
('F0583_4', 'F0583')
('F0583_5', 'F0583')
('F0583_6', 'F0583')
('F0583_7', 'F0583')
('F0605_1', 'F0605')
('F0605_2', 'F0605')
('F0605_3', 'F0605')
('F0611_1', 'F0611')
('F0611_2', 'F0611')
('F0611_3', 'F0611')
('F0611_4', 'F0611')
('F0645_1', 'F0645')
('F0645_2', 'F0645')
('F0645_3', 'F0645')
('F0645_4', 'F0645')
('F0645_5', 'F0645')
('F0645_6', 'F0645')
('F0645_7', 'F0645')
('F0645_8', 'F0645')
('F0662_1', 'F0662')
('F0662_2', 'F0662')
('F0662_3', 'F0662')
('F0662_4', 'F0662')
('F0684_1', 'F0684')
('F0684_2', 'F0684')
('F0684_3', 'F0684')
('F0684_4', 'F0684')
('F0684_5', 'F0684')
('F0684_6', 'F0684')
('F0691_1', 'F0691')
('F0691_2', 'F0691')
('F0691_3', 'F0691')
('F0691_4', 'F0691')
('F0692_1', 'F0692')
('F0692_2', 'F0692')
('F0692_3', 'F0692')
('F0692_4', 'F0692')
('F0708_1', 'F0708')
('F0708_10', 'F0708')
('F0708_2', 'F0708')
('F0708_3', 'F0708')
('F0708_4', 'F0708')
('F0708_5', 'F0708')
('F0708_6', 'F0708')
('F0708_7', 'F0708')
('F0708_8', 'F0708')
('F0708_9', 'F0708')
('F0743_1', 'F0743')
('F0743_2', 'F0743')
('F0743_3', 'F0743')
('F0743_4', 'F0743')
('F0743_5', 'F0743')
('F0767_1', 'F0767')
('F0767_2', 'F0767')
('F0767_3', 'F0767')
('F0767_4', 'F0767')
('F0767_5', 'F0767')
('F0767_6', 'F0767')
('F0770_1', 'F0770')
('F0770_2', 'F0770')
('F0770_3', 'F0770')
('F0770_4', 'F0770')
('F0770_5', 'F0770')
('F0773_1', 'F0773')
('F0773_2', 'F0773')
('F0773_3', 'F0773')
('F0773_4', 'F0773')
('F0773_5', 'F0773')
('F0773_6', 'F0773')
('F0778_1', 'F0778')
('F0778_2', 'F0778')
('F0778_3', 'F0778')
('F0778_4', 'F0778')
('F0793_1', 'F0793')
('F0793_2', 'F0793')
('F0793_3', 'F0793')
('F0793_4', 'F0793')
('F0810_1', 'F0810')
('F0810_2', 'F0810')
('F0810_3', 'F0810')
('F0838_1', 'F0838')
('F0838_2', 'F0838')
('F0838_3', 'F0838')
('F0838_4', 'F0838')
('F0838_5', 'F0838')
('F0838_6', 'F0838')
('F0838_7', 'F0838')
('F0843_1', 'F0843')
('F0843_2', 'F0843')
('F0843_3', 'F0843')
('F0843_4', 'F0843')
('F0843_5', 'F0843')
('F0844_1', 'F0844')
('F0844_2', 'F0844')
('F0844_3', 'F0844')
('F0844_4', 'F0844')
('F0844_5', 'F0844')
('F0847_1', 'F0847')
('F0847_2', 'F0847')
('F0847_3', 'F0847')
('F0850_1', 'F0850')
('F0850_2', 'F0850')
('F0850_3', 'F0850')
('F0850_4', 'F0850')
('F0850_5', 'F0850')
('F0869_1', 'F0869')
('F0869_2', 'F0869')
('F0869_3', 'F0869')
('F0874_1', 'F0874')
('F0874_2', 'F0874')
('F0874_3', 'F0874')
('F0874_4', 'F0874')
('F0874_5', 'F0874')
('F0874_6', 'F0874')
('F0875_1', 'F0875')
('F0875_2', 'F0875')
('F0875_3', 'F0875')
('F0875_4', 'F0875')
('F0889_1', 'F0889')
('F0889_2', 'F0889')
('F0889_3', 'F0889')
('F0889_4', 'F0889')
('F0894_1', 'F0894')
('F0894_2', 'F0894')
('F0894_3', 'F0894')
('F0896_1', 'F0896')
('F0896_2', 'F0896')
('F0896_3', 'F0896')
('F0896_4', 'F0896')
('F0896_5', 'F0896')
('F0926_1', 'F0926')
('F0926_2', 'F0926')
('F0926_3', 'F0926')
('F0926_4', 'F0926')
('F0926_5', 'F0926')
('F0926_6', 'F0926')
('F0944_1', 'F0944')
('F0944_2', 'F0944')
('F0944_3', 'F0944')
('F0944_4', 'F0944')
('F0951_1', 'F0951')
('F0951_2', 'F0951')
('F0951_3', 'F0951')
('F0954_1', 'F0954')
('F0954_2', 'F0954')
('F0954_3', 'F0954')
('F0954_4', 'F0954')
('F0954_5', 'F0954')
('F0959_1', 'F0959')
('F0959_2', 'F0959')
('F0959_3', 'F0959')
('F0959_4', 'F0959')
('F0959_5', 'F0959')
('F0960_1', 'F0960')
('F0960_2', 'F0960')
('F0960_3', 'F0960')
('F0960_4', 'F0960')
('F0960_5', 'F0960')
('F0960_6', 'F0960')
('F0972_1', 'F0972')
('F0972_2', 'F0972')
('F0972_3', 'F0972')
('F0972_4', 'F0972')
('F0972_5', 'F0972')
('F0984_1', 'F0984')
('F0984_2', 'F0984')
('F0984_3', 'F0984')
('F0984_4', 'F0984')
('F0984_5', 'F0984')
('F0984_6', 'F0984')
('F0984_7', 'F0984')
('F0997_1', 'F0997')
('F0997_2', 'F0997')
('F0997_3', 'F0997')
('F0997_4', 'F0997')
('F1003_1', 'F1003')
('F1003_2', 'F1003')
('F1003_3', 'F1003')
('F1003_4', 'F1003')
('F1003_5', 'F1003')
('F1003_6', 'F1003')
('F1003_7', 'F1003')

Let's look at an example

In [9]:
assignment_task = "('F1003_7', 'F1003')"

In [10]:
df = assignment_tasks_dfs[assignment_task]
df.head()

,,,,birthplace_distance,surname_distance,birthdate_distance,person_to_assign_name_other_person_middlename_distance,other_person_name_person_to_assign_middlename_distance,gender_male,other_person_gender_male,distance,sons_distance,daughters_distance,...,grandmothers_distance,grandfathers_distance,granddaughters_distance,grandsons_distance,nieces_distance,nephews_distance,aunts_distance,uncles_distance,kinship,assignment_task
person_to_assign_id,person_to_assign_family_id,family_person_id,family_id,,,,,,,,,,,,,,,,,,,,,
F1003_7,F1003,F1003_1,F1003,NaN,NaN,NaN,NaN,NaN,False,True,0.842923,0.516733,0.495550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,child,"('F1003_7', 'F1003')"
F0528_4,F0528,F1003_1,F1003,NaN,NaN,NaN,NaN,NaN,True,True,0.967962,0.707393,0.805582,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F1003_7', 'F1003')"
F0684_5,F0684,F1003_1,F1003,NaN,NaN,NaN,NaN,NaN,False,True,1.056817,0.906362,0.984361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F1003_7', 'F1003')"
F0691_4,F0691,F1003_1,F1003,NaN,NaN,NaN,NaN,NaN,False,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F1003_7', 'F1003')"
F0144_8,F0144,F1003_1,F1003,NaN,NaN,NaN,NaN,NaN,True,True,0.909613,0.954381,1.051683,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other,"('F1003_7', 'F1003')"

In [11]:
with open('files/FIW_family_dfs.pkl', 'rb') as pickle_file:
    family_dfs = load(pickle_file)

In [12]:
family_dfs['F1003']

     1  2  3  4  5  6  7             Name Gender
MID
1    0  5  4  4  4  4  4            jamie      m
2    5  0  4  4  4  4  4  juliette norton      f
3    1  1  0  2  2  2  2            buddy      m
4    1  1  2  0  2  2  2            river      m
5    1  1  2  2  0  2  2            poppy      f
6    1  1  2  2  2  0  2            daisy      f
7    1  1  2  2  2  2  0            petal      f

In [13]:
X = df.drop(columns=['kinship', 'assignment_task'], axis=1)
y = df['kinship']

In [14]:
probs = rf.predict_proba(X)
probs

array([[9.62222222e-01, 3.69444444e-02, 8.33333333e-04, 0.00000000e+00],
       [6.05555556e-02, 9.35000000e-01, 4.44444444e-03, 0.00000000e+00],
       [4.44444444e-03, 9.91111111e-01, 4.44444444e-03, 0.00000000e+00],
       [1.46463300e-02, 9.48766438e-01, 1.77025054e-02, 1.88847267e-02],
       [1.33333333e-02, 9.86666667e-01, 0.00000000e+00, 0.00000000e+00],
       [2.22222222e-03, 9.97777778e-01, 0.00000000e+00, 0.00000000e+00],
       [6.19047619e-03, 9.93809524e-01, 0.00000000e+00, 0.00000000e+00],
       [4.24349206e-01, 5.75650794e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.33333333e-02, 9.86666667e-01, 0.00000000e+00, 0.00000000e+00],
       [9.73492063e-01, 2.65079365e-02, 0.00000000e+00, 0.00000000e+00],
       [6.19206349e-02, 9.38079365e-01, 0.00000000e+00, 0.00000000e+00],
       [5.00000000e-03, 9.87777778e-01, 7.22222222e-03, 0.00000000e+00],
       [1.24720282e-02, 9.60243894e-01, 1.13942996e-02, 1.58897780e-02],
       [3.33333333e-03, 9.96666667e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.59989418e-01, 6.40010582e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30555556e-02, 9.66944444e-01, 0.00000000e+00, 0.00000000e+00],
       [1.11111111e-03, 3.88888889e-03, 3.88888889e-03, 9.91111111e-01],
       [3.88888889e-03, 8.80888889e-01, 5.97777778e-02, 5.54444444e-02],
       [0.00000000e+00, 9.94444444e-01, 0.00000000e+00, 5.55555556e-03],
       [1.46463300e-02, 9.48766438e-01, 1.77025054e-02, 1.88847267e-02],
       [3.80952381e-03, 9.91904762e-01, 3.33333333e-03, 9.52380952e-04],
       [0.00000000e+00, 9.93333333e-01, 6.66666667e-03, 0.00000000e+00],
       [2.50000000e-03, 9.70944444e-01, 2.65555556e-02, 0.00000000e+00],
       [6.11111111e-03, 5.86312169e-01, 3.32777778e-02, 3.74298942e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.57185185e-01, 3.94814815e-02, 3.33333333e-03],
       [0.00000000e+00, 7.48518519e-02, 2.22222222e-02, 9.02925926e-01],
       [0.00000000e+00, 8.00291486e-01, 8.05339105e-02, 1.19174603e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.46463300e-02, 9.48766438e-01, 1.77025054e-02, 1.88847267e-02],
       [6.66666667e-03, 9.86666667e-01, 6.66666667e-03, 0.00000000e+00],
       [0.00000000e+00, 9.84777778e-01, 5.00000000e-03, 1.02222222e-02],
       [2.66666667e-03, 9.54000000e-01, 1.33333333e-02, 3.00000000e-02],
       [0.00000000e+00, 7.69164502e-01, 5.52402597e-02, 1.75595238e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.66666667e-03, 8.69354497e-01, 3.09735450e-02, 9.30052910e-02],
       [0.00000000e+00, 1.90476190e-03, 0.00000000e+00, 9.98095238e-01],
       [2.22222222e-03, 9.01634921e-01, 3.61904762e-02, 5.99523810e-02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.24720282e-02, 9.60243894e-01, 1.13942996e-02, 1.58897780e-02],
       [0.00000000e+00, 9.87777778e-01, 1.22222222e-02, 0.00000000e+00],
       [0.00000000e+00, 9.93333333e-01, 6.66666667e-03, 0.00000000e+00],
       [2.44444444e-03, 9.89222222e-01, 0.00000000e+00, 8.33333333e-03],
       [0.00000000e+00, 7.55873016e-01, 4.11904762e-02, 2.02936508e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.54629630e-01, 9.61005291e-02, 4.92698413e-02],
       [0.00000000e+00, 1.90476190e-03, 0.00000000e+00, 9.98095238e-01],
       [6.66666667e-03, 8.22909646e-01, 9.16984127e-02, 7.87252747e-02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.24720282e-02, 9.60243894e-01, 1.13942996e-02, 1.58897780e-02],
       [0.00000000e+00, 9.96666667e-01, 3.33333333e-03, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.33333333e-03, 9.80611111e-01, 1.05555556e-02, 7.50000000e-03],
       [0.00000000e+00, 8.08269841e-01, 4.30634921e-02, 1.48666667e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.03783069e-01, 5.20529101e-02, 4.41640212e-02]])

In [15]:
rf.classes_

array(['child', 'other', 'parent', 'sibling'], dtype=object)

In [16]:
import numpy as np

classes = rf.classes_
not_relative_index = int(np.where(classes == 'other')[0][0])
child_index = int(np.where(classes == 'child')[0][0])
parent_index = int(np.where(classes == 'parent')[0][0])
sibling_index = int(np.where(classes == 'sibling')[0][0])
not_relative_index, child_index, parent_index, sibling_index

(1, 0, 2, 3)

In [17]:
X["not_relative_probability"] = probs[:, not_relative_index]
X["child_probability"] = probs[:, child_index]
X["parent_probability"] = probs[:, parent_index]
X["sibling_probability"] = probs[:, sibling_index]

In [18]:
X.sort_values(by="not_relative_probability")[["sibling_probability", "child_probability", "parent_probability"]].head()

                                                                           sibling_probability  \
person_to_assign_id person_to_assign_family_id family_person_id family_id
F1003_7             F1003                      F1003_6          F1003                 0.998095
                                               F1003_5          F1003                 0.998095
                                               F1003_3          F1003                 0.991111
                                               F1003_2          F1003                 0.000000
                                               F1003_1          F1003                 0.000000

                                                                           child_probability  \
person_to_assign_id person_to_assign_family_id family_person_id family_id
F1003_7             F1003                      F1003_6          F1003               0.000000
                                               F1003_5          F1003               0.000000
                                               F1003_3          F1003               0.001111
                                               F1003_2          F1003               0.973492
                                               F1003_1          F1003               0.962222

                                                                           parent_probability
person_to_assign_id person_to_assign_family_id family_person_id family_id
F1003_7             F1003                      F1003_6          F1003                0.000000
                                               F1003_5          F1003                0.000000
                                               F1003_3          F1003                0.003889
                                               F1003_2          F1003                0.000000
                                               F1003_1          F1003                0.000833

In [19]:
assignment_task = "('F1003_7', 'F1003')"

In [20]:
df_sorted_suggestions = X.sort_values(by="not_relative_probability")[["sibling_probability", "child_probability", "parent_probability"]]
for index in df_sorted_suggestions.index:
    row = df_sorted_suggestions.loc[index]
    sorted_row = row.sort_values(ascending=False)
    for probs_index in sorted_row.index:
        proba = sorted_row.loc[probs_index]
        if proba > 0.01:
            relative = probs_index[:probs_index.find('_')]
            print(f"{index[0]} is a {relative} of {index[2]}\t - probability {round(proba, 3)}")

F1003_7 is a sibling of F1003_6	 - probability 0.998
F1003_7 is a sibling of F1003_5	 - probability 0.998
F1003_7 is a sibling of F1003_3	 - probability 0.991
F1003_7 is a child of F1003_2	 - probability 0.973
F1003_7 is a child of F1003_1	 - probability 0.962
F1003_7 is a sibling of F1003_4	 - probability 0.903
F1003_7 is a parent of F1003_4	 - probability 0.022
F0229_3 is a child of F1003_1	 - probability 0.424
F0229_3 is a sibling of F1003_3	 - probability 0.374
F0229_3 is a parent of F1003_3	 - probability 0.033
F0229_3 is a child of F1003_2	 - probability 0.36
F0229_3 is a sibling of F1003_5	 - probability 0.203
F0229_3 is a parent of F1003_5	 - probability 0.041
F0229_3 is a sibling of F1003_4	 - probability 0.176
F0229_3 is a parent of F1003_4	 - probability 0.055
F0528_4 is a sibling of F1003_4	 - probability 0.119
F0528_4 is a parent of F1003_4	 - probability 0.081
F0229_3 is a sibling of F1003_6	 - probability 0.149
F0229_3 is a parent of F1003_6	 - probability 0.043
F0528_4 is a parent of F1003_6	 - probability 0.092
F0528_4 is a sibling of F1003_6	 - probability 0.079
F0097_2 is a parent of F1003_5	 - probability 0.096
F0097_2 is a sibling of F1003_5	 - probability 0.049
F0097_2 is a sibling of F1003_4	 - probability 0.093
F0097_2 is a parent of F1003_4	 - probability 0.031
F0528_4 is a parent of F1003_3	 - probability 0.06
F0528_4 is a sibling of F1003_3	 - probability 0.055
F0528_4 is a sibling of F1003_5	 - probability 0.06
F0528_4 is a parent of F1003_5	 - probability 0.036
F0097_2 is a parent of F1003_6	 - probability 0.052
F0097_2 is a sibling of F1003_6	 - probability 0.044
F0528_4 is a child of F1003_1	 - probability 0.061
F0528_4 is a child of F1003_2	 - probability 0.062
F0691_4 is a sibling of F1003_4	 - probability 0.019
F0691_4 is a parent of F1003_4	 - probability 0.018
F0691_4 is a child of F1003_4	 - probability 0.015
F0691_4 is a sibling of F1003_1	 - probability 0.019
F0691_4 is a parent of F1003_1	 - probability 0.018
F0691_4 is a child of F1003_1	 - probability 0.015
F0691_4 is a sibling of F1003_3	 - probability 0.019
F0691_4 is a parent of F1003_3	 - probability 0.018
F0691_4 is a child of F1003_3	 - probability 0.015
F0380_6 is a sibling of F1003_4	 - probability 0.03
F0380_6 is a parent of F1003_4	 - probability 0.013
F0097_2 is a parent of F1003_3	 - probability 0.039
F0691_4 is a sibling of F1003_5	 - probability 0.016
F0691_4 is a child of F1003_5	 - probability 0.012
F0691_4 is a parent of F1003_5	 - probability 0.011
F0691_4 is a sibling of F1003_6	 - probability 0.016
F0691_4 is a child of F1003_6	 - probability 0.012
F0691_4 is a parent of F1003_6	 - probability 0.011
F0691_4 is a sibling of F1003_2	 - probability 0.016
F0691_4 is a child of F1003_2	 - probability 0.012
F0691_4 is a parent of F1003_2	 - probability 0.011
F0097_2 is a child of F1003_2	 - probability 0.033
F0380_6 is a parent of F1003_3	 - probability 0.027
F0380_6 is a parent of F1003_6	 - probability 0.011
F0875_2 is a sibling of F1003_4	 - probability 0.01
F0144_8 is a child of F1003_1	 - probability 0.013
F0097_2 is a child of F1003_1	 - probability 0.013
F0144_8 is a parent of F1003_5	 - probability 0.012

Suggestions grouped by people

In [21]:
groups_by_suggested_people = X.groupby(level=['person_to_assign_id', 'person_to_assign_family_id'])

In [22]:
columns = ['child_probability', 'parent_probability',
       'sibling_probability']

In [23]:
for person, df in groups_by_suggested_people:
    df = df.sort_values(by=columns, key=lambda x: df[columns].max(axis=1), ascending=False)
    for index in df.index:
        row = df_sorted_suggestions.loc[index]
        sorted_row = row.sort_values(ascending=False)
        for probs_index in sorted_row.index:
            proba = sorted_row.loc[probs_index]
            if proba > 0.01:
                relative = probs_index[:probs_index.find('_')]
                print(f"{index[0]} is a {relative} of {index[2]}\t - probability {round(proba, 3)}")
    print()

F0097_2 is a parent of F1003_5	 - probability 0.096
F0097_2 is a sibling of F1003_5	 - probability 0.049
F0097_2 is a sibling of F1003_4	 - probability 0.093
F0097_2 is a parent of F1003_4	 - probability 0.031
F0097_2 is a parent of F1003_6	 - probability 0.052
F0097_2 is a sibling of F1003_6	 - probability 0.044
F0097_2 is a parent of F1003_3	 - probability 0.039
F0097_2 is a child of F1003_2	 - probability 0.033
F0097_2 is a child of F1003_1	 - probability 0.013

F0144_8 is a child of F1003_1	 - probability 0.013
F0144_8 is a parent of F1003_5	 - probability 0.012

F0229_3 is a child of F1003_1	 - probability 0.424
F0229_3 is a sibling of F1003_3	 - probability 0.374
F0229_3 is a parent of F1003_3	 - probability 0.033
F0229_3 is a child of F1003_2	 - probability 0.36
F0229_3 is a sibling of F1003_5	 - probability 0.203
F0229_3 is a parent of F1003_5	 - probability 0.041
F0229_3 is a sibling of F1003_4	 - probability 0.176
F0229_3 is a parent of F1003_4	 - probability 0.055
F0229_3 is a sibling of F1003_6	 - probability 0.149
F0229_3 is a parent of F1003_6	 - probability 0.043

F0380_6 is a sibling of F1003_4	 - probability 0.03
F0380_6 is a parent of F1003_4	 - probability 0.013
F0380_6 is a parent of F1003_3	 - probability 0.027
F0380_6 is a parent of F1003_6	 - probability 0.011


F0528_4 is a sibling of F1003_4	 - probability 0.119
F0528_4 is a parent of F1003_4	 - probability 0.081
F0528_4 is a parent of F1003_6	 - probability 0.092
F0528_4 is a sibling of F1003_6	 - probability 0.079
F0528_4 is a child of F1003_2	 - probability 0.062
F0528_4 is a child of F1003_1	 - probability 0.061
F0528_4 is a sibling of F1003_5	 - probability 0.06
F0528_4 is a parent of F1003_5	 - probability 0.036
F0528_4 is a parent of F1003_3	 - probability 0.06
F0528_4 is a sibling of F1003_3	 - probability 0.055


F0691_4 is a sibling of F1003_1	 - probability 0.019
F0691_4 is a parent of F1003_1	 - probability 0.018
F0691_4 is a child of F1003_1	 - probability 0.015
F0691_4 is a sibling of F1003_3	 - probability 0.019
F0691_4 is a parent of F1003_3	 - probability 0.018
F0691_4 is a child of F1003_3	 - probability 0.015
F0691_4 is a sibling of F1003_4	 - probability 0.019
F0691_4 is a parent of F1003_4	 - probability 0.018
F0691_4 is a child of F1003_4	 - probability 0.015
F0691_4 is a sibling of F1003_2	 - probability 0.016
F0691_4 is a child of F1003_2	 - probability 0.012
F0691_4 is a parent of F1003_2	 - probability 0.011
F0691_4 is a sibling of F1003_5	 - probability 0.016
F0691_4 is a child of F1003_5	 - probability 0.012
F0691_4 is a parent of F1003_5	 - probability 0.011
F0691_4 is a sibling of F1003_6	 - probability 0.016
F0691_4 is a child of F1003_6	 - probability 0.012
F0691_4 is a parent of F1003_6	 - probability 0.011

F0875_2 is a sibling of F1003_4	 - probability 0.01

F1003_7 is a sibling of F1003_5	 - probability 0.998
F1003_7 is a sibling of F1003_6	 - probability 0.998
F1003_7 is a sibling of F1003_3	 - probability 0.991
F1003_7 is a child of F1003_2	 - probability 0.973
F1003_7 is a child of F1003_1	 - probability 0.962
F1003_7 is a sibling of F1003_4	 - probability 0.903
F1003_7 is a parent of F1003_4	 - probability 0.022

Metrics on all experiments

In [24]:
test_df["not_relative_probability"] = test_proba[:, not_relative_index]
test_df["child_probability"] = test_proba[:, child_index]
test_df["parent_probability"] = test_proba[:, parent_index]
test_df["sibling_probability"] = test_proba[:, sibling_index]

In [25]:
from pickle import load


with open('files/FIW_test_families.pkl', 'rb') as pickle_file:
    families = load(pickle_file)

In [42]:
top_1 = []
top_3 = []
top_5 = []

top_1_family = []
top_3_family = []
top_5_family = []

dfs = []

for assignment_task, df in test_df.groupby(by='assignment_task'):
    df['df_index'] = df.index
    df = df[['child_probability', 'parent_probability', 'sibling_probability', 'kinship', 'not_relative_probability', 'df_index']]
    df = df.melt(id_vars=['kinship', 'not_relative_probability', 'df_index'],
    value_vars=['child_probability', 'parent_probability', 'sibling_probability'],
    var_name="score_type",
    value_name="probability")


    for index in df.index:
        row = df.loc[index]
        kinship = row['kinship']
        score_type = row['score_type']
        idx = row['df_index']
        family_id = idx[3]
        correct_relative = (kinship == 'sibling' and score_type == 'sibling_probability') or (kinship == 'parent' and score_type == 'parent_probability') or (kinship == 'child' and score_type == 'child_probability')
        correct_family = idx[1] == family_id
        correct_guess = correct_relative and correct_family

        df.loc[index, 'correct_guess'] = correct_guess
        df.loc[index, 'correct_family'] = correct_family

        if kinship == 'parent':
            person = families[family_id].members[idx[2]]
            person_to_assign = families[idx[1]].members[idx[0]]
            if person_to_assign.gender == "Male" and len(person.father) > 0 and not person_to_assign in person.father:
                df.loc[index, "possible"] = False
            elif person_to_assign.gender == "Female" and len(person.mother) > 0 and not person_to_assign in person.mother:
                df.loc[index, "possible"] = False
            else:
                df.loc[index, "possible"] = True
        else:
            df.loc[index, "possible"] = True

    df = df[df['possible']]

    df = df.sort_values(by=['probability'], ascending=False)

    top_1.append(df.iloc[0]["correct_guess"])
    top_3.append(df.iloc[:3]["correct_guess"].any())
    top_5.append(df.iloc[:5]["correct_guess"].any())

    top_1_family.append(df.iloc[0]["correct_family"])
    top_3_family.append(df.iloc[:3]["correct_family"].any())
    top_5_family.append(df.iloc[:5]["correct_family"].any())

    dfs.append(df)

In [27]:
print(f"Top-1: {sum(top_1) / len(top_1)}")
print(f"Top-3: {sum(top_3) / len(top_3)}")
print(f"Top-5: {sum(top_5) / len(top_5)}")

print(f"Top-1 family: {sum(top_1_family) / len(top_1_family)}")
print(f"Top-3 family: {sum(top_3_family) / len(top_3_family)}")
print(f"Top-5 family: {sum(top_5_family) / len(top_5_family)}")

Top-1: 0.5086206896551724
Top-3: 0.6357758620689655
Top-5: 0.7004310344827587
Top-1 family: 0.6163793103448276
Top-3 family: 0.7456896551724138
Top-5 family: 0.8060344827586207

If we select other people non-randomly:

In [145]:
from tqdm import tqdm
import ast
from src.short_list_selection import select_closest


all_people = []
for k, v in families.items():
    all_people += list(v.members.values())

in_top_guesses = []
for el in tqdm(set(test_df['assignment_task'])):
    person_id, family_id = ast.literal_eval(el)
    family = families[family_id]
    person = family.members[person_id]
    family_excluding = family.create_family_excluding_a_person(person_id)#
    all_other_people = [p for p in all_people if p.family_id != family_id] + [person]
    top_choices = select_closest(family_excluding, all_other_people, 10)
    in_top_guesses.append(person_id in [el[2] for el in top_choices])

100%|██████████| 464/464 [00:19<00:00, 23.24it/s]

In [146]:
np.mean(in_top_guesses)

np.float64(0.46336206896551724)

In [147]:
len(families), len(all_people)

(86, 476)

Example

In [150]:
person_id in [el[2] for el in top_choices]

True

In [151]:
person_id

'F0959_3'

In [134]:
import src.classification_utils as classification_utils

In [163]:
tasks = classification_utils.make_classification_tasks_with_known_answers(family, [el[0] for el in top_choices])

In [165]:
df = classification_utils.make_classification_df(tasks, answers_known=True)

In [166]:
df = classification_utils.predict_probabilities(df, rf, non_feature_cols=['kinship'])

In [167]:
top_suggestions = classification_utils.get_top_suggestions(df)

In [168]:
top_suggestions = classification_utils.filter_suggestions(top_suggestions, families)

In [169]:
top_suggestions.columns

Index(['kinship', 'not_relative_probability', 'df_index', 'score_type',
       'probability', 'possible'],
      dtype='object')

In [170]:
top_suggestions = classification_utils.get_correctness(top_suggestions)

In [171]:
top_suggestions

,kinship,not_relative_probability,df_index,score_type,probability,possible,correct_guess,correct_family
102,sibling,0.007778,"(F0959_3, F0959, F0959_4, F0959)",sibling_probability,0.978111,True,True,True
20,child,0.032778,"(F0959_3, F0959, F0959_1, F0959)",child_probability,0.967222,True,True,True
101,sibling,0.015111,"(F0959_3, F0959, F0959_2, F0959)",sibling_probability,0.957270,True,True,True
23,child,0.084492,"(F0959_3, F0959, F0959_5, F0959)",child_probability,0.908841,True,True,True
15,other,0.204238,"(F0117_5, F0117, F0959_5, F0959)",child_probability,0.795762,True,False,False
...,...,...,...,...,...,...,...,...
107,other,0.856563,"(F0080_6, F0080, F0959_5, F0959)",sibling_probability,0.000000,True,False,False
115,other,0.454078,"(F0293_10, F0293, F0959_5, F0959)",sibling_probability,0.000000,True,False,False
112,other,0.448981,"(F0293_10, F0293, F0959_1, F0959)",sibling_probability,0.000000,True,False,False
116,other,0.502119,"(F0874_3, F0874, F0959_1, F0959)",sibling_probability,0.000000,True,False,False
119,other,0.536633,"(F0874_3, F0874, F0959_5, F0959)",sibling_probability,0.000000,True,False,False

In [172]:
classification_utils.evaluate_top_metrics(top_suggestions)

(True, np.True_, np.True_, True, np.True_, np.True_)

In [181]:
top_1_list = []
top_3_list = []
top_5_list = []
top_1_family_list = []
top_3_family_list = []
top_5_family_list = []
for el in tqdm(set(test_df['assignment_task'])):
    person_id, family_id = ast.literal_eval(el)
    family = families[family_id]
    person = family.members[person_id]
    family_excluding = family.create_family_excluding_a_person(person_id)#
    all_other_people = [p for p in all_people if p.family_id != family_id] + [person]
    top_choices = select_closest(family_excluding, all_other_people, 10)
    top_people = [el[0] for el in top_choices]
    tasks = classification_utils.make_classification_tasks_with_known_answers(family, top_people)
    df = classification_utils.make_classification_df(tasks, answers_known=True)
    df = classification_utils.predict_probabilities(df, rf, non_feature_cols=['kinship'])
    top_suggestions = classification_utils.get_top_suggestions(df)
    top_suggestions = classification_utils.filter_suggestions(top_suggestions, families)
    top_suggestions = classification_utils.get_correctness(top_suggestions)
    top_1, top_3, top_5, top_1_family, top_3_family, top_5_family = classification_utils.evaluate_top_metrics(top_suggestions)
    top_1_family_list.append(top_1_family)
    top_3_family_list.append(top_3_family)
    top_5_family_list.append(top_5_family)
    top_1_list.append(top_1)
    top_3_list.append(top_3)
    top_5_list.append(top_5)

100%|██████████| 464/464 [02:09<00:00,  3.59it/s]

In [182]:
print(f"Top-1: {sum(top_1_list) / len(top_1_family_list)}")
print(f"Top-3: {sum(top_3_list) / len(top_3_family_list)}")
print(f"Top-5: {sum(top_5_list) / len(top_5_family_list)}")

print(f"Top-1 family: {sum(top_1_family_list) / len(top_1_family_list)}")
print(f"Top-3 family: {sum(top_3_family_list) / len(top_3_family_list)}")
print(f"Top-5 family: {sum(top_5_family_list) / len(top_5_family_list)}")

Top-1: 0.23706896551724138
Top-3: 0.2952586206896552
Top-5: 0.32112068965517243
Top-1 family: 0.2629310344827586
Top-3 family: 0.33405172413793105
Top-5 family: 0.3599137931034483

In [184]:

for n in [1, 5, 10, 15, 30]:
    print(n)
    top_1_list = []
    top_3_list = []
    top_5_list = []
    top_1_family_list = []
    top_3_family_list = []
    top_5_family_list = []
    for el in tqdm(set(test_df['assignment_task'])):
        person_id, family_id = ast.literal_eval(el)
        family = families[family_id]
        person = family.members[person_id]
        family_excluding = family.create_family_excluding_a_person(person_id)#
        all_other_people = [p for p in all_people if p.family_id != family_id] + [person]
        top_choices = select_closest(family_excluding, all_other_people, n)
        top_people = [el[0] for el in top_choices]
        tasks = classification_utils.make_classification_tasks_with_known_answers(family, top_people)
        df = classification_utils.make_classification_df(tasks, answers_known=True)
        df = classification_utils.predict_probabilities(df, rf, non_feature_cols=['kinship'])
        top_suggestions = classification_utils.get_top_suggestions(df)
        top_suggestions = classification_utils.filter_suggestions(top_suggestions, families)
        top_suggestions = classification_utils.get_correctness(top_suggestions)
        top_1, top_3, top_5, top_1_family, top_3_family, top_5_family = classification_utils.evaluate_top_metrics(top_suggestions)
        top_1_family_list.append(top_1_family)
        top_3_family_list.append(top_3_family)
        top_5_family_list.append(top_5_family)
        top_1_list.append(top_1)
        top_3_list.append(top_3)
        top_5_list.append(top_5)

    print(f"Top-1: {sum(top_1_list) / len(top_1_family_list)}")
    print(f"Top-3: {sum(top_3_list) / len(top_3_family_list)}")
    print(f"Top-5: {sum(top_5_list) / len(top_5_family_list)}")

    print(f"Top-1 family: {sum(top_1_family_list) / len(top_1_family_list)}")
    print(f"Top-3 family: {sum(top_3_family_list) / len(top_3_family_list)}")
    print(f"Top-5 family: {sum(top_5_family_list) / len(top_5_family_list)}")

1

100%|██████████| 464/464 [01:01<00:00,  7.51it/s]

Top-1: 0.22198275862068967
Top-3: 0.2413793103448276
Top-5: 0.25646551724137934
Top-1 family: 0.28448275862068967
Top-3 family: 0.28448275862068967
Top-5 family: 0.28448275862068967
5

100%|██████████| 464/464 [01:31<00:00,  5.10it/s]

Top-1: 0.21767241379310345
Top-3: 0.2650862068965517
Top-5: 0.29094827586206895
Top-1 family: 0.24568965517241378
Top-3 family: 0.3081896551724138
Top-5 family: 0.33405172413793105
10

100%|██████████| 464/464 [02:20<00:00,  3.31it/s]

Top-1: 0.23706896551724138
Top-3: 0.2952586206896552
Top-5: 0.32112068965517243
Top-1 family: 0.2629310344827586
Top-3 family: 0.33405172413793105
Top-5 family: 0.3599137931034483
15

100%|██████████| 464/464 [03:03<00:00,  2.53it/s]

Top-1: 0.23922413793103448
Top-3: 0.2995689655172414
Top-5: 0.3297413793103448
Top-1 family: 0.2650862068965517
Top-3 family: 0.33836206896551724
Top-5 family: 0.3728448275862069
30

100%|██████████| 464/464 [03:18<00:00,  2.33it/s]

Top-1: 0.2349137931034483
Top-3: 0.28879310344827586
Top-5: 0.3297413793103448
Top-1 family: 0.25646551724137934
Top-3 family: 0.32112068965517243
Top-5 family: 0.375

In [185]:
for n in [1]:
    print(n)
    top_1_list = []
    top_3_list = []
    top_5_list = []
    top_1_family_list = []
    top_3_family_list = []
    top_5_family_list = []
    for el in tqdm(set(test_df['assignment_task'])):
        person_id, family_id = ast.literal_eval(el)
        family = families[family_id]
        person = family.members[person_id]
        family_excluding = family.create_family_excluding_a_person(person_id)#
        all_other_people = [p for p in all_people if p.family_id != family_id] + [person]
        top_choices = select_closest(family_excluding, all_other_people, n)
        top_people = [el[0] for el in top_choices]
        tasks = classification_utils.make_classification_tasks_with_known_answers(family, top_people)
        df = classification_utils.make_classification_df(tasks, answers_known=True)
        df = classification_utils.predict_probabilities(df, rf, non_feature_cols=['kinship'])
        top_suggestions = classification_utils.get_top_suggestions(df)
        top_suggestions = classification_utils.filter_suggestions(top_suggestions, families)
        top_suggestions = classification_utils.get_correctness(top_suggestions)
        top_1, top_3, top_5, top_1_family, top_3_family, top_5_family = classification_utils.evaluate_top_metrics(top_suggestions)
        top_1_family_list.append(top_1_family)
        top_3_family_list.append(top_3_family)
        top_5_family_list.append(top_5_family)
        top_1_list.append(top_1)
        top_3_list.append(top_3)
        top_5_list.append(top_5)

    print(f"Top-1: {sum(top_1_list) / len(top_1_family_list)}")
    print(f"Top-3: {sum(top_3_list) / len(top_3_family_list)}")
    print(f"Top-5: {sum(top_5_list) / len(top_5_family_list)}")

    print(f"Top-1 family: {sum(top_1_family_list) / len(top_1_family_list)}")
    print(f"Top-3 family: {sum(top_3_family_list) / len(top_3_family_list)}")
    print(f"Top-5 family: {sum(top_5_family_list) / len(top_5_family_list)}")

1

100%|██████████| 464/464 [00:16<00:00, 28.41it/s]

Top-1: 0.22198275862068967
Top-3: 0.2413793103448276
Top-5: 0.25646551724137934
Top-1 family: 0.28448275862068967
Top-3 family: 0.28448275862068967
Top-5 family: 0.28448275862068967