In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('query.csv')
df

,person,personLabel,personImage,personGender,child,childLabel,childImage,childGender
0,http://www.wikidata.org/entity/Q1484216,"John Romita, Sr.",http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q2570,John Romita Jr.,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
1,http://www.wikidata.org/entity/Q314834,Robert Vaughn,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q2593,Matthew Vaughn,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
2,http://www.wikidata.org/entity/Q328667,Rajmund Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
3,http://www.wikidata.org/entity/Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072,http://www.wikidata.org/entity/Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
4,http://www.wikidata.org/entity/Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072,http://www.wikidata.org/entity/Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
...,...,...,...,...,...,...,...,...
9995,http://www.wikidata.org/entity/Q12036810,Michal Suchánek,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q11132344,Berenika Suchánková,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072
9996,http://www.wikidata.org/entity/Q5955380,Julio Jung,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q11090551,Julio Jung Duvauchelle,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9997,http://www.wikidata.org/entity/Q11469470,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q11258485,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9998,http://www.wikidata.org/entity/Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q11259379,Tasuku Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9999,http://www.wikidata.org/entity/Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,http://www.wikidata.org/entity/Q11259381,Tokio Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097

In [ ]:
df["person"] = df["person"].apply(lambda x: x.split('/')[-1])
df["child"] = df["child"].apply(lambda x: x.split('/')[-1])
df

,person,personLabel,personImage,personGender,child,childLabel,childImage,childGender
0,Q1484216,"John Romita, Sr.",http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q2570,John Romita Jr.,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
1,Q314834,Robert Vaughn,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q2593,Matthew Vaughn,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
2,Q328667,Rajmund Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
3,Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
4,Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
...,...,...,...,...,...,...,...,...
9995,Q12036810,Michal Suchánek,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q11132344,Berenika Suchánková,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581072
9996,Q5955380,Julio Jung,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q11090551,Julio Jung Duvauchelle,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9997,Q11469470,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q11258485,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9998,Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q11259379,Tasuku Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097
9999,Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097,Q11259381,Tokio Emoto,http://commons.wikimedia.org/wiki/Special:File...,http://www.wikidata.org/entity/Q6581097

In [ ]:
df["personGender"] = df["personGender"].apply(lambda x: x.split('/')[-1])
df["childGender"] = df["childGender"].apply(lambda x: x.split('/')[-1])
gender_dict = {"Q6581097": "male", "Q6581072": "female"}
df["personGender"] = df["personGender"].apply(lambda x: gender_dict[x] if x in gender_dict else x)
df["childGender"] = df["childGender"].apply(lambda x: gender_dict[x] if x in gender_dict else x)
df

,person,personLabel,personImage,personGender,child,childLabel,childImage,childGender
0,Q1484216,"John Romita, Sr.",http://commons.wikimedia.org/wiki/Special:File...,male,Q2570,John Romita Jr.,http://commons.wikimedia.org/wiki/Special:File...,male
1,Q314834,Robert Vaughn,http://commons.wikimedia.org/wiki/Special:File...,male,Q2593,Matthew Vaughn,http://commons.wikimedia.org/wiki/Special:File...,male
2,Q328667,Rajmund Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,male,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,male
3,Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,female,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,male
4,Q3266318,Jadwiga Kaczyńska,http://commons.wikimedia.org/wiki/Special:File...,female,Q2757,Lech Kaczyński,http://commons.wikimedia.org/wiki/Special:File...,male
...,...,...,...,...,...,...,...,...
9995,Q12036810,Michal Suchánek,http://commons.wikimedia.org/wiki/Special:File...,male,Q11132344,Berenika Suchánková,http://commons.wikimedia.org/wiki/Special:File...,female
9996,Q5955380,Julio Jung,http://commons.wikimedia.org/wiki/Special:File...,male,Q11090551,Julio Jung Duvauchelle,http://commons.wikimedia.org/wiki/Special:File...,male
9997,Q11469470,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,male,Q11258485,Shinjirō Yamamura,http://commons.wikimedia.org/wiki/Special:File...,male
9998,Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,male,Q11259379,Tasuku Emoto,http://commons.wikimedia.org/wiki/Special:File...,male
9999,Q873921,Akira Emoto,http://commons.wikimedia.org/wiki/Special:File...,male,Q11259381,Tokio Emoto,http://commons.wikimedia.org/wiki/Special:File...,male

In [ ]:
len(set(df["person"])), len(set(df["child"])), len(set(df["person"]).union(set(df["child"]))), len(set(df["person"]).intersection(set(df["child"])))

(7750, 7913, 15211, 452)

In [ ]:
people_list = list(set(df["person"]).union(set(df["child"])))

In [ ]:
person_num_dict = {}
for i in range(len(people_list)):
  person_num_dict[people_list[i]] = i

In [ ]:
import numpy as np


graph = np.zeros((len(people_list), len(people_list)))
for i in range(len(df)):
  graph[person_num_dict[df["child"][i]]][person_num_dict[df["person"][i]]] = 1

In [ ]:
from scipy.sparse import csr_array
from scipy.sparse.csgraph import connected_components

graph = csr_array(graph)
n_components, labels = connected_components(csgraph=graph, directed=True, return_labels=True)

In [ ]:
n_components

6260

In [ ]:
labels

array([   0,    1,    2, ..., 1305, 3224,  807], dtype=int32)

In [ ]:
id_to_family_num = {person_id: family_num for person_id, family_num in zip(people_list, labels)}

In [ ]:
families = {}
for i in range(n_components):
  family_index_list = np.where(labels == i)[0]
  family_ids_list = [people_list[index] for index in family_index_list]
  family_graph = graph[family_index_list][:, family_index_list].toarray()
  family_graph_df = pd.DataFrame(family_graph, index=family_ids_list, columns=family_ids_list).astype(int)
  families[i] = {"ids": family_ids_list, "graph": family_graph_df}

In [ ]:
families[id_to_family_num["Q1484216"]]

{'ids': ['Q1484216', 'Q2570'],
 'graph':           Q1484216  Q2570
 Q1484216         0      0
 Q2570            1      0}

Q1484216 is Q2570's parent

In [ ]:
child_parents_dict = {}
for parent, child in zip(df["person"], df["child"]):
  if child not in child_parents_dict:
    child_parents_dict[child] = {parent}
  else:
    child_parents_dict[child].add(parent)

In [ ]:
person1_list = []
person2_list = []
relationship_list = []
family_list = []
for child in child_parents_dict:
  for parent in child_parents_dict[child]:
    person1_list.append(parent)
    person2_list.append(child)
    relationship_list.append("parent - child")
    family_list.append(id_to_family_num[parent])
    if parent in child_parents_dict:
      for grandparent in child_parents_dict[parent]:
        person1_list.append(grandparent)
        person2_list.append(child)
        relationship_list.append("grandparent - child")
        family_list.append(id_to_family_num[grandparent])

In [ ]:
from tqdm import tqdm

for child_1 in tqdm(child_parents_dict):
  family_id = id_to_family_num[child_1]
  for child_2 in families[family_id]["ids"]:
    if child_2 in child_parents_dict and child_1 != child_2:
      if child_parents_dict[child_1] == child_parents_dict[child_2]:
        person1_list.append(child_1)
        person2_list.append(child_2)
        relationship_list.append("siblings")
        family_list.append(id_to_family_num[child_1])

100%|██████████| 7913/7913 [00:00<00:00, 186559.68it/s]

In [ ]:
pairs_df = pd.DataFrame({"person1": person1_list, "person2": person2_list, "relationship": relationship_list, "family": family_list})
pairs_df

         person1    person2    relationship  family
0       Q1484216      Q2570  parent - child    2681
1        Q314834      Q2593  parent - child    4026
2       Q3266318      Q2757  parent - child    4479
3        Q328667      Q2757  parent - child    4479
4        Q238402      Q2831  parent - child     542
...          ...        ...             ...     ...
13195  Q10860948    Q467187        siblings    5884
13196  Q10967627   Q4687826        siblings    5018
13197  Q11058950   Q7418393        siblings     155
13198  Q11259379  Q11259381        siblings    1022
13199  Q11259381  Q11259379        siblings    1022

[13200 rows x 4 columns]

In [ ]:
pairs_df.relationship.value_counts()

relationship
parent - child         9330
siblings               2952
grandparent - child     918
Name: count, dtype: int64

In [ ]:
person_to_pictures = {}
for i in range(len(df)):
  if df["person"][i] not in person_to_pictures:
    person_to_pictures[df["person"][i]] = [df["personImage"][i]]
  else:
    person_to_pictures[df["person"][i]].append(df["personImage"][i])
  if df["child"][i] not in person_to_pictures:
    person_to_pictures[df["child"][i]] = [df["childImage"][i]]
  else:
    person_to_pictures[df["child"][i]].append(df["childImage"][i])

In [ ]:
picture_pairs_df = pd.DataFrame(columns=["person1", "person2", "image1", "image2", "relationship", "family"])
for i in tqdm(range(len(pairs_df))):
  for picture1 in person_to_pictures[pairs_df["person1"][i]]:
    for picture2 in person_to_pictures[pairs_df["person2"][i]]:
      picture_pairs_df.loc[len(picture_pairs_df)] = [pairs_df["person1"][i], pairs_df["person2"][i], picture1, picture2, pairs_df["relationship"][i], pairs_df["family"][i]]

100%|██████████| 13200/13200 [01:51<00:00, 118.41it/s]

In [ ]:
picture_pairs_df

,person1,person2,image1,image2,relationship,family
0,Q1484216,Q2570,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,2681
1,Q314834,Q2593,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,4026
2,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,4479
3,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,4479
4,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,4479
...,...,...,...,...,...,...
44873,Q10860948,Q467187,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,siblings,5884
44874,Q10967627,Q4687826,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,siblings,5018
44875,Q11058950,Q7418393,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,siblings,155
44876,Q11259379,Q11259381,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,siblings,1022
44877,Q11259381,Q11259379,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,siblings,1022

In [ ]:
len(families)

6260

In [ ]:
from sklearn.model_selection import train_test_split


train_families, test_families = train_test_split(list(families.keys()), test_size=0.2, random_state=42)
val_families, test_families = train_test_split(test_families, test_size=0.5, random_state=42)

In [ ]:
train_picture_pairs_df = picture_pairs_df[picture_pairs_df["family"].isin(train_families)]
val_picture_pairs_df = picture_pairs_df[picture_pairs_df["family"].isin(val_families)]
test_picture_pairs_df = picture_pairs_df[picture_pairs_df["family"].isin(test_families)]

In [ ]:
picture_to_person = {}
for i in range(len(df)):
  picture_to_person[df["personImage"][i]] = df["person"][i]
  picture_to_person[df["childImage"][i]] = df["child"][i]

In [ ]:
train_pictures = [el for el in picture_to_person if id_to_family_num[picture_to_person[el]] in set(train_families)]
val_pictures = [el for el in picture_to_person if id_to_family_num[picture_to_person[el]] in set(val_families)]
test_pictures = [el for el in picture_to_person if id_to_family_num[picture_to_person[el]] in set(test_families)]

In [ ]:
counter = 0

train_picture_pairs_non_relatives_df = pd.DataFrame(columns=["person1", "person2", "image1", "image2", "relationship"])
while len(train_picture_pairs_non_relatives_df) < len(train_picture_pairs_df):
  i = np.random.randint(0, len(train_pictures))
  j = np.random.randint(0, len(train_pictures))
  if i != j:
    family_1 = id_to_family_num[picture_to_person[train_pictures[i]]]
    family_2 = id_to_family_num[picture_to_person[train_pictures[j]]]
    if family_1 != family_2:
      row = [picture_to_person[train_pictures[i]], picture_to_person[train_pictures[j]], train_pictures[i], train_pictures[j], None]
      train_picture_pairs_non_relatives_df.loc[len(train_picture_pairs_non_relatives_df)] = row
  counter += 1
  if counter % 1000 == 0:
    print(counter)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000

In [ ]:
train_pairs = pd.concat([train_picture_pairs_df.drop(columns=["family"]), train_picture_pairs_non_relatives_df])
train_pairs

,person1,person2,image1,image2,relationship
0,Q1484216,Q2570,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child
1,Q314834,Q2593,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child
2,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child
3,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child
4,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child
...,...,...,...,...,...
38868,Q571190,Q260955,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None
38869,Q3482430,Q1053620,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None
38870,Q1480,Q16297911,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None
38871,Q28755,Q601495,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None
38872,Q1814977,Q119923,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None

In [ ]:
train_pairs["are_related"] = train_pairs["relationship"].apply(lambda x: 1 if x != None else 0)
train_pairs

,person1,person2,image1,image2,relationship,are_related
0,Q1484216,Q2570,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
1,Q314834,Q2593,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
2,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
3,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
4,Q3266318,Q2757,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
...,...,...,...,...,...,...
38868,Q571190,Q260955,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
38869,Q3482430,Q1053620,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
38870,Q1480,Q16297911,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
38871,Q28755,Q601495,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
38872,Q1814977,Q119923,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0

In [ ]:
counter = 0

val_picture_pairs_non_relatives_df = pd.DataFrame(columns=["person1", "person2", "image1", "image2", "relationship"])
while len(val_picture_pairs_non_relatives_df) < len(val_picture_pairs_df):
  i = np.random.randint(0, len(val_pictures))
  j = np.random.randint(0, len(val_pictures))
  if i != j:
    family_1 = id_to_family_num[picture_to_person[val_pictures[i]]]
    family_2 = id_to_family_num[picture_to_person[val_pictures[j]]]
    if family_1 != family_2:
      row = [picture_to_person[val_pictures[i]], picture_to_person[val_pictures[j]], val_pictures[i], val_pictures[j], None]
      val_picture_pairs_non_relatives_df.loc[len(val_picture_pairs_non_relatives_df)] = row
  counter += 1
  if counter % 1000 == 0:
    print(counter)


val_pairs = pd.concat([val_picture_pairs_df.drop(columns=["family"]), val_picture_pairs_non_relatives_df])
val_pairs["are_related"] = val_pairs["relationship"].apply(lambda x: 1 if x != None else 0)
val_pairs

1000
2000
3000

,person1,person2,image1,image2,relationship,are_related
171,Q7496354,Q1784,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
189,Q6761976,Q13133,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
190,Q6761976,Q13133,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
540,Q4818309,Q3772,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
615,Q155385,Q4414,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
...,...,...,...,...,...,...
3121,Q4416179,Q9210252,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
3122,Q82918,Q1184381,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
3123,Q3761938,Q6387843,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
3124,Q12880750,Q16367961,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
3125,Q1225,Q16305973,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0

In [ ]:
counter = 0

test_picture_pairs_non_relatives_df = pd.DataFrame(columns=["person1", "person2", "image1", "image2", "relationship"])
while len(test_picture_pairs_non_relatives_df) < len(test_picture_pairs_df):
  i = np.random.randint(0, len(test_pictures))
  j = np.random.randint(0, len(test_pictures))
  if i != j:
    family_1 = id_to_family_num[picture_to_person[test_pictures[i]]]
    family_2 = id_to_family_num[picture_to_person[test_pictures[j]]]
    if family_1 != family_2:
      row = [picture_to_person[test_pictures[i]], picture_to_person[test_pictures[j]], test_pictures[i], test_pictures[j], None]
      test_picture_pairs_non_relatives_df.loc[len(test_picture_pairs_non_relatives_df)] = row
  counter += 1
  if counter % 1000 == 0:
    print(counter)


test_pairs = pd.concat([test_picture_pairs_df.drop(columns=["family"]), test_picture_pairs_non_relatives_df])
test_pairs["are_related"] = test_pairs["relationship"].apply(lambda x: 1 if x != None else 0)
test_pairs

1000
2000

,person1,person2,image1,image2,relationship,are_related
226,Q12085,Q12105,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
264,Q7109912,Q12878,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
266,Q7177,Q12927,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
267,Q7177,Q12927,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
268,Q7177,Q12927,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,parent - child,1
...,...,...,...,...,...,...
2874,Q2621015,Q178344,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
2875,Q1264872,Q3144896,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
2876,Q655550,Q350075,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
2877,Q46117503,Q7161085,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0
2878,Q4439403,Q1442367,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,None,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train_pairs.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/train_pairs.csv', index=False)

In [ ]:
val_pairs.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/val_pairs.csv', index=False)

In [ ]:
test_pairs.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/test_pairs.csv', index=False)

In [ ]:
df.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/query_result.csv', index=False)

In [ ]:
pairs_df.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/relative_pairs.csv', index=False)

In [ ]:
picture_pairs_df.to_csv('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/relative_picture_pairs.csv', index=False)

In [ ]:
import pickle

with open('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/families.pkl', 'wb') as f:
  pickle.dump(families, f)

In [ ]:
import json


person_id_to_family_num = {person_id: int(family_num) for person_id, family_num in zip(people_list, labels)}
with open('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/person_id_to_family_num.json', 'w') as f:
  json.dump(person_id_to_family_num, f)

In [ ]:
df['personImage'][0]

'http://commons.wikimedia.org/wiki/Special:FilePath/John%20Romita%20Sr%2C%202006.jpg'

In [ ]:
import requests


requests.get(df['personImage'][0]).content

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\x00\xff\xe1\x1dVExif\x00\x00MM\x00*\x00\x00\x00\x08\x00\x0b\x01\x0f\x00\x02\x00\x00\x00\x06\x00\x00\x08\x9e\x01\x10\x00\x02\x00\x00\x00\x1b\x00\x00\x08\xa4\x01\x12\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x08\xc0\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x08\xc8\x01(\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x011\x00\x02\x00\x00\x00/\x00\x00\x08\xd0\x012\x00\x02\x00\x00\x00\x14\x00\x00\t\x00\x02\x13\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x87i\x00\x04\x00\x00\x00\x01\x00\x00\t\x14\xea\x1c\x00\x07\x00\x00\x08\x0c\x00\x00\x00\x92\x00\x00\x14\x08\x1c\xea\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Canon\x00Canon EOS DIGITAL REBEL XT\x00\x00\x00\x00\x00H\x00\x00\x00\x01\x00\x00\x00H\x00\x00\x00\x01Microsoft Windows Photo Gallery 6.0.6000.16386\x00\x002010:09:02 18:26:56\x00\x00\x1c\x82\x9a\x00\x05\x00\x00\x00\x01\x00\x00\x12v\x82\x9d\x00\x05\x00\x00\x00\x01\x00\x00\x12~\x88"\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x88\'\x00\x03\x00\x00\x00\x01\x01\x90\x00\x00\x90\x00\x00\x07\x00\x00\x00\x040221\x90\x03\x00\x02\x00\x00\x00\x14\x00\x00\x12\x86\x90\x04\x00\x02\x00\x00\x00\x14\x00\x00\x12\x9a\x91\x01\x00\x07\x00\x00\x00\x04\x01\x02\x03\x00\x92\x01\x00\n\x00\x00\x00\x01\x00\x00\x12\xae\x92\x02\x00\x05\x00\x00\x00\x01\x00\x00\x12\xb6\x92\x04\x00\n\x00\x00\x00\x01\x00\x00\x12\xbe\x92\x07\x00\x03\x00\x00\x00\x01\x00\x05\x00\x00\x92\t\x00\x03\x00\x00\x00\x01\x00\x19\x00\x00\x92\n\x00\x05\x00\x00\x00\x01\x00\x00\x12\xc6\x92\x86\x00\x07\x00\x00\x01\x08\x00\x00\x12\xce\xa0\x00\x00\x07\x00\x00\x00\x040100\xa0\x01\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\xa0\x02\x00\x04\x00\x00\x00\x01\x00\x00\x01\x14\xa0\x03\x00\x04\x00\x00\x00\x01\x00\x00\x01J\xa2\x0e\x00\x05\x00\x00\x00\x01\x00\x00\x13\xd6\xa2\x0f\x00\x05\x00\x00\x00\x01\x00\x00\x13\xde\xa2\x10\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\xa4\x01\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\xa4\x02\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\xa4\x03\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\xa4\x06\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\xa4 \x00\x02\x00\x00\x00!\x00\x00\x13\xe6\xea\x1c\x00\x07\x00\x00\x08\x0c\x00\x00\nj\x00\x00\x00\x00\x1c\xea\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00<\x00\x00\x002\x00\x00\x00\n2006:07:21 19:03:46\x002006:07:21 19:03:46\x00\x00\x05\xe8*\x00\x01\x00\x00\x00\x04\xa4\xd4\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00*\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\xbc\x00\x00\x00\x03j\x00#(\x00\x00\x00\x02F0987E7D98897477EBF15D2284F6F5916\x00\x00\x00\x06\x01\x03\

In [ ]:
import os


os.makedirs('images', exist_ok=True)

In [ ]:
len(set(df['personImage']))

7912

In [ ]:
len(set(df['childImage']))

8111

In [ ]:
len(set(df['personImage'])) + len(set(df['childImage']))

16023

In [ ]:
len(set(df['personImage']).union(set(df['childImage'])))

15543

In [ ]:
images = list(set(df['personImage']).union(set(df['childImage'])))
images[:10]

['http://commons.wikimedia.org/wiki/Special:FilePath/Tiit%20Sokk%202006.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Mon%20Cherie%202%201980-1-.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Hamza%20Shahbaz%20%28cropped%29.png',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Mary%20Dresselhuys.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Peter%20Parker%201995.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/%E7%8E%8B%E6%B0%B8%E6%85%B6.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Georges%20Lautner%201966.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Schuurs%20RG22%20%2827%29%20%2852144293024%29%20%28cropped%29.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Mauricio%20Macri%202016.jpg',
 'http://commons.wikimedia.org/wiki/Special:FilePath/Milla%20Jovovich%20Oct%20%28cropped%29.jpg']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

os.makedirs('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/images', exist_ok=True)

In [ ]:
num_names_dict = {}
for i in tqdm(range(len(images))):
    num_names_dict[i] = images[i].split('/')[-1]

NameError: name 'tqdm' is not defined

In [ ]:
with open('/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/files/picture_nums_to_urls.json', 'w') as f:
  json.dump(num_names_dict, f)

In [ ]:
requests.get(images[2]).status_code

403

In [ ]:
!wget http://commons.wikimedia.org/wiki/Special:FilePath/Senadores%20da%2057%C2%AA%20Legislatura%20%2852689452405%29.jpg

--2025-01-21 03:31:41--  http://commons.wikimedia.org/wiki/Special:FilePath/Senadores%20da%2057%C2%AA%20Legislatura%20%2852689452405%29.jpg
Resolving commons.wikimedia.org (commons.wikimedia.org)... 208.80.153.224, 2620:0:860:ed1a::1
Connecting to commons.wikimedia.org (commons.wikimedia.org)|208.80.153.224|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://commons.wikimedia.org/wiki/Special:FilePath/Senadores%20da%2057%C2%AA%20Legislatura%20%2852689452405%29.jpg [following]
--2025-01-21 03:31:41--  https://commons.wikimedia.org/wiki/Special:FilePath/Senadores%20da%2057%C2%AA%20Legislatura%20%2852689452405%29.jpg
Connecting to commons.wikimedia.org (commons.wikimedia.org)|208.80.153.224|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://commons.wikimedia.org/wiki/Special:FilePath/Senadores_da_57%C2%AA_Legislatura_(52689452405).jpg [following]
--2025-01-21 03:31:41--  https://commons.wikimedia.org/wiki/Special:FilePath/Senadores_da_57%C2%AA_Legislatura_(52689452405).jpg
Reusing existing connection to commons.wikimedia.org:443.
HTTP request sent, awaiting response... 302 Found
Location: https://commons.wikimedia.org/wiki/Special:Redirect/file/Senadores_da_57%C2%AA_Legislatura_(52689452405).jpg [following]
--2025-01-21 03:31:41--  https://commons.wikimedia.org/wiki/Special:Redirect/file/Senadores_da_57%C2%AA_Legislatura_(52689452405).jpg
Reusing existing connection to commons.wikimedia.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://upload.wikimedia.org/wikipedia/commons/3/3e/Senadores_da_57%C2%AA_Legislatura_%2852689452405%29.jpg [following]
--2025-01-21 03:31:41--  https://upload.wikimedia.org/wikipedia/commons/3/3e/Senadores_da_57%C2%AA_Legislatura_%2852689452405%29.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.153.240, 2620:0:860:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.153.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 912211 (891K) [image/jpeg]
Saving to: ‘Senadores da 57ª Legislatura (52689452405).jpg’

Senadores da 57ª Le 100%[===================>] 890.83K  4.20MB/s    in 0.2s

2025-01-21 03:31:41 (4.20 MB/s) - ‘Senadores da 57ª Legislatura (52689452405).jpg’ saved [912211/912211]

In [ ]:
images[0]

'http://commons.wikimedia.org/wiki/Special:FilePath/Senadores%20da%2057%C2%AA%20Legislatura%20%2852689452405%29.jpg'

In [ ]:
from time import sleep
from tqdm import tqdm
import requests


headers = {'User-Agent': 'Visual_Kinship_Recognition/0.1 (treyvish.ilya@gmail.com)'}
num_names_dict = {}
for i in tqdm(range(100)):
  while True:
    response = requests.get(images[i], headers)
    if response.status_code == 200:
      with open(f'/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/images/{i}.jpg', 'wb') as f:
        f.write(response.content)
      num_names_dict[i] = images[i].split('/')[-1]
      break
    else:
      print(f"Request failed with status code {response.status_code}. Retrying in 10 seconds...")
      sleep(10)

  0%|          | 0/100 [00:00<?, ?it/s]

Request failed with status code 403. Retrying in 10 seconds...

  0%|          | 0/100 [00:04<?, ?it/s]

KeyboardInterrupt:

In [ ]:
for i in tqdm(range(11353, len(images))):
  with open(f'/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/images/{i}.jpg', 'wb') as f:
    f.write(requests.get(images[i]).content)
    num_names_dict[i] = images[i].split('/')[-1]

100%|██████████| 4190/4190 [38:18<00:00,  1.82it/s]

In [ ]:
!du -sh "/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/images/"

335M	/content/drive/MyDrive/Genotek kinship recognition/Wikipedia dataset/images/