## Exploring and preprocessing the SiblingsDB dataset

Getting the dataset which is described [here](https://areeweb.polito.it/ricerca/cgvg/siblingsDB.html)

In [1]:
!wget https://www.dropbox.com/scl/fi/t9zeok6etatdpxsp54xih/SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu&e=1&dl=0

--2025-01-14 20:08:59--  https://www.dropbox.com/scl/fi/t9zeok6etatdpxsp54xih/SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com/cd/0/inline/CiNENDfG96ygckrlu5UHM3ybTl36ovC8xOikRLGiY2U-VjkdKxJsDBhNp1b5Ym8Gk5UyY8PA3KITjzjqHiqfFjENLNYtAllCuxaBc-7IsUwMOnPdlqHJ8kVKY9g-nwXIcONw-sFZCOg2H6d3nYGqI4ce/file# [following]
--2025-01-14 20:09:00--  https://uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com/cd/0/inline/CiNENDfG96ygckrlu5UHM3ybTl36ovC8xOikRLGiY2U-VjkdKxJsDBhNp1b5Ym8Gk5UyY8PA3KITjzjqHiqfFjENLNYtAllCuxaBc-7IsUwMOnPdlqHJ8kVKY9g-nwXIcONw-sFZCOg2H6d3nYGqI4ce/file
Resolving uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com (uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com)... 162.125.3.15, 2620:100:6019:15::a27d:40f
Connecting to uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com (uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com)|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/CiNAp0TKkfihV5DrhFhB2kl_pg7JYQEBgAx-iIe1u_e8tiGvKtguRRqSqWye9up8lFaTI4BSDJOp8ePxZkaDROs-LDrsq6ACZQ1ALPhMnpImG1y8NzBlw120TH0ort8LY6iiDSHxShUmgxGyKTUuaMCmVRElnkuK4RtlYcM4CVi2UioeJVKKdgMu6LtrlP48ui89uy7LRRnN1fWuHMkwMcDeH5DWs5qOdsLLdX6lLAXSC1dE6qiKE2f85_qfUgtuuCMKFQYjDOHHMX6yZ1x-O43cLlMUb0y__WhRhC3dsE7uwfqPerq-fvd8gFtcEa-i9TauGbd9Ej6TW8v56BFuEMCV_j1jYT3A1C_oT_JMfkFelLPgVAriHlXSSOohZlFSbtQ/file [following]
--2025-01-14 20:09:01--  https://uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com/cd/0/inline2/CiNAp0TKkfihV5DrhFhB2kl_pg7JYQEBgAx-iIe1u_e8tiGvKtguRRqSqWye9up8lFaTI4BSDJOp8ePxZkaDROs-LDrsq6ACZQ1ALPhMnpImG1y8NzBlw120TH0ort8LY6iiDSHxShUmgxGyKTUuaMCmVRElnkuK4RtlYcM4CVi2UioeJVKKdgMu6LtrlP48ui89uy7LRRnN1fWuHMkwMcDeH5DWs5qOdsLLdX6lLAXSC1dE6qiKE2f85_qfUgtuuCMKFQYjDOHHMX6yZ1x-O43cLlMUb0y__WhRhC3dsE7uwfqPerq-fvd8gFtcEa-i9TauGbd9Ej6TW8v56BFuEMCV_j1jYT3A1C_oT_JMfkFelLPgVAriHlXSSOohZlFSbtQ/file
Reusing existing connection to uc8a3ce5ef09d8b7f68c280bc529.dl-eu.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 7737446972 (7.2G) [application/zip]
Saving to: ‘SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu’

SiblingsDB.zip?rlke 100%[===================>]   7.21G  29.1MB/s    in 6m 29s

2025-01-14 20:15:32 (19.0 MB/s) - ‘SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu’ saved [7737446972/7737446972]

In [2]:
! unzip /content/SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu -d /content/SiblingsDB

Archive:  /content/SiblingsDB.zip?rlkey=fluq21wjavok4jn849v09lgmu
   creating: /content/SiblingsDB/DBs/
   creating: /content/SiblingsDB/DBs/HQf/
   creating: /content/SiblingsDB/DBs/HQfp/
   creating: /content/SiblingsDB/DBs/HQfps/
   creating: /content/SiblingsDB/DBs/HQfps/100/
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0152.csv
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0152.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0154.csv
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0154.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0156.csv
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0156.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0159.csv
 extracting: /content/SiblingsDB/DBs/HQfps/100/_DSC0159.jpg
   creating: /content/SiblingsDB/DBs/HQfps/104/
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0181.csv
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0181.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0183.csv
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0183.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0185.csv
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0185.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0186.csv
 extracting: /content/SiblingsDB/DBs/HQfps/104/_DSC0186.jpg
   creating: /content/SiblingsDB/DBs/HQfps/106/
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0195.csv
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0195.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0198.csv
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0198.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0199.csv
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0199.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0201.csv
 extracting: /content/SiblingsDB/DBs/HQfps/106/_DSC0201.jpg
   creating: /content/SiblingsDB/DBs/HQfps/107/
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0204.csv
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0204.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0206.csv
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0206.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0207.csv
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0207.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0209.csv
 extracting: /content/SiblingsDB/DBs/HQfps/107/_DSC0209.jpg
   creating: /content/SiblingsDB/DBs/HQfps/108/
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0211.csv
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0211.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0212.csv
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0212.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0213.csv
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0213.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0214.csv
 extracting: /content/SiblingsDB/DBs/HQfps/108/_DSC0214.jpg
   creating: /content/SiblingsDB/DBs/HQfps/109/
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0215.csv
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0215.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0218.csv
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0218.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0222.csv
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0222.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0223.csv
 extracting: /content/SiblingsDB/DBs/HQfps/109/_DSC0223.jpg
   creating: /content/SiblingsDB/DBs/HQfps/110/
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0225.csv
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0225.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0228.csv
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0228.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0230.csv
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0230.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0232.csv
 extracting: /content/SiblingsDB/DBs/HQfps/110/_DSC0232.jpg
   creating: /content/SiblingsDB/DBs/HQfps/111/
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0234.csv
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0234.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0236.csv
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0236.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0238.csv
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0238.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0239.csv
 extracting: /content/SiblingsDB/DBs/HQfps/111/_DSC0239.jpg
   creating: /content/SiblingsDB/DBs/HQfps/112/
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0241.csv
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0241.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0243.csv
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0243.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0245.csv
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0245.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0247.csv
 extracting: /content/SiblingsDB/DBs/HQfps/112/_DSC0247.jpg
   creating: /content/SiblingsDB/DBs/HQfps/113/
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0250.csv
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0250.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0252.csv
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0252.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0253.csv
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0253.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0255.csv
 extracting: /content/SiblingsDB/DBs/HQfps/113/_DSC0255.jpg
   creating: /content/SiblingsDB/DBs/HQfps/114/
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0257.csv
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0257.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0259.csv
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0259.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0261.csv
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0261.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0263.csv
 extracting: /content/SiblingsDB/DBs/HQfps/114/_DSC0263.jpg
   creating: /content/SiblingsDB/DBs/HQfps/115/
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0266.csv
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0266.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0267.csv
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0267.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0269.csv
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0269.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0271.csv
 extracting: /content/SiblingsDB/DBs/HQfps/115/_DSC0271.jpg
   creating: /content/SiblingsDB/DBs/HQfps/118/
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0274.csv
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0274.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0276.csv
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0276.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0280.csv
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0280.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0282.csv
 extracting: /content/SiblingsDB/DBs/HQfps/118/_DSC0282.jpg
   creating: /content/SiblingsDB/DBs/HQfps/119/
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0284.csv
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0284.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0285.csv
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0285.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0289.csv
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0289.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0292.csv
 extracting: /content/SiblingsDB/DBs/HQfps/119/_DSC0292.jpg
   creating: /content/SiblingsDB/DBs/HQfps/122/
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0294.csv
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0294.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0296.csv
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0296.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0298.csv
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0298.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0300.csv
 extracting: /content/SiblingsDB/DBs/HQfps/122/_DSC0300.jpg
   creating: /content/SiblingsDB/DBs/HQfps/123/
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0302.csv
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0302.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0304.csv
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0304.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0306.csv
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0306.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0308.csv
 extracting: /content/SiblingsDB/DBs/HQfps/123/_DSC0308.jpg
   creating: /content/SiblingsDB/DBs/HQfps/124/
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0309.csv
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0309.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0313.csv
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0313.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0315.csv
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0315.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0318.csv
 extracting: /content/SiblingsDB/DBs/HQfps/124/_DSC0318.jpg
   creating: /content/SiblingsDB/DBs/HQfps/125/
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0320.csv
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0320.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0321.csv
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0321.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0326.csv
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0326.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0328.csv
 extracting: /content/SiblingsDB/DBs/HQfps/125/_DSC0328.jpg
   creating: /content/SiblingsDB/DBs/HQfps/126/
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0346.csv
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0346.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0348.csv
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0348.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0350.csv
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0350.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0352.csv
 extracting: /content/SiblingsDB/DBs/HQfps/126/_DSC0352.jpg
   creating: /content/SiblingsDB/DBs/HQfps/127/
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0355.csv
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0355.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0357.csv
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0357.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0359.csv
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0359.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0360.csv
 extracting: /content/SiblingsDB/DBs/HQfps/127/_DSC0360.jpg
   creating: /content/SiblingsDB/DBs/HQfps/128/
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0362.csv
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0362.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0364.csv
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0364.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0365.csv
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0365.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0367.csv
 extracting: /content/SiblingsDB/DBs/HQfps/128/_DSC0367.jpg
   creating: /content/SiblingsDB/DBs/HQfps/129/
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0369.csv
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0369.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0371.csv
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0371.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0375.csv
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0375.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0377.csv
 extracting: /content/SiblingsDB/DBs/HQfps/129/_DSC0377.jpg
   creating: /content/SiblingsDB/DBs/HQfps/130/
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0379.csv
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0379.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0381.csv
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0381.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0382.csv
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0382.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0384.csv
 extracting: /content/SiblingsDB/DBs/HQfps/130/_DSC0384.jpg
   creating: /content/SiblingsDB/DBs/HQfps/133/
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0401.csv
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0401.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0403.csv
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0403.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0404.csv
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0404.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0405.csv
 extracting: /content/SiblingsDB/DBs/HQfps/133/_DSC0405.jpg
   creating: /content/SiblingsDB/DBs/HQfps/137/
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0441.csv
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0441.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0443.csv
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0443.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0448.csv
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0448.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0449.csv
 extracting: /content/SiblingsDB/DBs/HQfps/137/_DSC0449.jpg
   creating: /content/SiblingsDB/DBs/HQfps/138/
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0452.csv
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0452.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0454.csv
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0454.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0455.csv
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0455.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0458.csv
 extracting: /content/SiblingsDB/DBs/HQfps/138/_DSC0458.jpg
   creating: /content/SiblingsDB/DBs/HQfps/143/
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0527.csv
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0527.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0529.csv
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0529.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0531.csv
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0531.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0533.csv
 extracting: /content/SiblingsDB/DBs/HQfps/143/_DSC0533.jpg
   creating: /content/SiblingsDB/DBs/HQfps/144/
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0534.csv
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0534.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0537.csv
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0537.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0538.csv
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0538.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0540.csv
 extracting: /content/SiblingsDB/DBs/HQfps/144/_DSC0540.jpg
   creating: /content/SiblingsDB/DBs/HQfps/145/
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0542.csv
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0542.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0543.csv
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0543.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0545.csv
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0545.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0547.csv
 extracting: /content/SiblingsDB/DBs/HQfps/145/_DSC0547.jpg
   creating: /content/SiblingsDB/DBs/HQfps/146/
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0550.csv
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0550.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0551.csv
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0551.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0553.csv
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0553.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0555.csv
 extracting: /content/SiblingsDB/DBs/HQfps/146/_DSC0555.jpg
   creating: /content/SiblingsDB/DBs/HQfps/148/
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0557.csv
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0557.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0558.csv
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0558.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0560.csv
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0560.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0562.csv
 extracting: /content/SiblingsDB/DBs/HQfps/148/_DSC0562.jpg
   creating: /content/SiblingsDB/DBs/HQfps/149/
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0564.csv
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0564.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0566.csv
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0566.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0568.csv
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0568.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0570.csv
 extracting: /content/SiblingsDB/DBs/HQfps/149/_DSC0570.jpg
   creating: /content/SiblingsDB/DBs/HQfps/150/
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0572.csv
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0572.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0574.csv
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0574.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0576.csv
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0576.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0578.csv
 extracting: /content/SiblingsDB/DBs/HQfps/150/_DSC0578.jpg
   creating: /content/SiblingsDB/DBs/HQfps/151/
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0579.csv
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0579.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0581.csv
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0581.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0583.csv
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0583.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0584.csv
 extracting: /content/SiblingsDB/DBs/HQfps/151/_DSC0584.jpg
   creating: /content/SiblingsDB/DBs/HQfps/152/
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0585.csv
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0585.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0587.csv
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0587.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0588.csv
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0588.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0590.csv
 extracting: /content/SiblingsDB/DBs/HQfps/152/_DSC0590.jpg
   creating: /content/SiblingsDB/DBs/HQfps/153/
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0592.csv
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0592.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0593.csv
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0593.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0595.csv
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0595.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0597.csv
 extracting: /content/SiblingsDB/DBs/HQfps/153/_DSC0597.jpg
   creating: /content/SiblingsDB/DBs/HQfps/154/
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0598.csv
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0598.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0603.csv
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0603.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0605.csv
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0605.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0607.csv
 extracting: /content/SiblingsDB/DBs/HQfps/154/_DSC0607.jpg
   creating: /content/SiblingsDB/DBs/HQfps/155/
 extracting: /content/SiblingsDB/DBs/HQfps/155/_DSC0609.csv
 extracting: /content/SiblingsDB/DBs/HQfps/155/_DSC0609.jpg
 extracting: /content/SiblingsDB/DBs/HQfps/155/_DSC0610.csv

Let's look at the dataset structure.

In [3]:
import os

os.listdir('/content/SiblingsDB')

['HQf_sibling_matrix.mat',
 'HQfps_sibling_matrix.mat',
 'HQfps.csv',
 'LQf.csv',
 'HQf.csv',
 'DBs',
 'SiblingsDB_license.pdf',
 'HQfp_sibling_matrix.mat',
 'SiblingsDB - content description 2.0.pdf',
 'HQfp.csv',
 'subjects.csv']

In [4]:
os.listdir('/content/SiblingsDB/DBs')

['HQfp', 'LQf', 'HQfps', 'HQf']

In [5]:
!sudo apt-get install tree

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  tree
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 47.9 kB of archives.
After this operation, 116 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tree amd64 2.0.2-1 [47.9 kB]
Fetched 47.9 kB in 0s (104 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package tree.
(Reading database ... 123632 files and directories currently installed.)
Preparing to unpack .../tree_2.0.2-1_amd64.deb ...
Unpacking tree (2.0.2-1) ...
Setting up tree (2.0.2-1) ...
Processing triggers for man-db (2.10.2-1) ...

In [6]:
!tree /content/SiblingsDB --filelimit 100

/content/SiblingsDB
├── DBs
│   ├── HQf  [180 entries exceeds filelimit, not opening dir]
│   ├── HQfp  [161 entries exceeds filelimit, not opening dir]
│   ├── HQfps  [115 entries exceeds filelimit, not opening dir]
│   └── LQf  [393 entries exceeds filelimit, not opening dir]
├── HQf.csv
├── HQfp.csv
├── HQfps.csv
├── HQfp_sibling_matrix.mat
├── HQfps_sibling_matrix.mat
├── HQf_sibling_matrix.mat
├── LQf.csv
├── SiblingsDB - content description 2.0.pdf
├── SiblingsDB_license.pdf
└── subjects.csv

5 directories, 10 files

In [7]:
!tree /content/SiblingsDB/DBs/HQf | head -20

/content/SiblingsDB/DBs/HQf
├── 1
│   ├── _DSC5755_1.csv
│   └── _DSC5755_1.jpg
├── 10
│   ├── _DSC5804.csv
│   └── _DSC5804.jpg
├── 100
│   ├── _DSC0152.csv
│   └── _DSC0152.jpg
├── 104
│   ├── _DSC0181.csv
│   └── _DSC0181.jpg
├── 106
│   ├── _DSC0195.csv
│   └── _DSC0195.jpg
├── 107
│   ├── _DSC0204.csv
│   └── _DSC0204.jpg
├── 108

In [8]:
!tree /content/SiblingsDB/DBs/HQfp | head -20

/content/SiblingsDB/DBs/HQfp
├── 1
│   ├── _DSC5755_1.csv
│   ├── _DSC5755_1.jpg
│   ├── _DSC5758_1.csv
│   └── _DSC5758_1.jpg
├── 10
│   ├── _DSC5804.csv
│   ├── _DSC5804.jpg
│   ├── _DSC5809.csv
│   └── _DSC5809.jpg
├── 100
│   ├── _DSC0152.csv
│   ├── _DSC0152.jpg
│   ├── _DSC0156.csv
│   └── _DSC0156.jpg
├── 104
│   ├── _DSC0181.csv
│   ├── _DSC0181.jpg
│   ├── _DSC0185.csv

In [9]:
!tree /content/SiblingsDB/DBs/HQfps | head -20

/content/SiblingsDB/DBs/HQfps
├── 100
│   ├── _DSC0152.csv
│   ├── _DSC0152.jpg
│   ├── _DSC0154.csv
│   ├── _DSC0154.jpg
│   ├── _DSC0156.csv
│   ├── _DSC0156.jpg
│   ├── _DSC0159.csv
│   └── _DSC0159.jpg
├── 104
│   ├── _DSC0181.csv
│   ├── _DSC0181.jpg
│   ├── _DSC0183.csv
│   ├── _DSC0183.jpg
│   ├── _DSC0185.csv
│   ├── _DSC0185.jpg
│   ├── _DSC0186.csv
│   └── _DSC0186.jpg
├── 106

In [10]:
!tree /content/SiblingsDB/DBs/LQf | head -20

/content/SiblingsDB/DBs/LQf
├── adams_louise.csv
├── adams_louise.jpg
├── adams_victoria.csv
├── adams_victoria.jpg
├── affleck_ben.csv
├── affleck_ben.jpg
├── affleck_casey.csv
├── affleck_casey.jpg
├── alba_jessica.csv
├── alba_jessica.jpg
├── alba_joshua.csv
├── alba_joshua.jpg
├── avati_antonio.csv
├── avati_antonio.jpg
├── avati_pupi.csv
├── avati_pupi.jpg
├── baldwin_alec.csv
├── baldwin_alec.jpg
├── baldwin_daniel.csv

These files have the information about sibling pairs:

In [11]:
import scipy.io
mat = scipy.io.loadmat('/content/SiblingsDB/HQf_sibling_matrix.mat')
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sat Mar 15 18:19:52 2014',
 '__version__': '1.0',
 '__globals__': [],
 'sibling_matrix': array([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 1, 1, 0]], dtype=uint8)}

These tables provide the information about the pairs of photos chosen for the experiments and the answers given by people:

In [12]:
import pandas as pd

HQf = pd.read_csv('/content/SiblingsDB/HQf.csv')
HQf

,unique couple ID,are they siblings?,# votes,Yes' answers,No' answers,first picture,second picture
0,0003_0001,1,443,250,193,3/DSC5751,1/DSC5755_1
1,0005_0001,-1,443,55,388,5/DSC5763,1/DSC5755_1
2,0006_0003,-1,444,36,408,6/DSC5760,3/DSC5751
3,0006_0005,1,444,232,212,6/DSC5760,5/DSC5763
4,0008_0007,1,443,141,302,8/DSC5774,7/DSC5769
...,...,...,...,...,...,...,...
199,0267_0266,1,444,155,289,267/DSC3077,266/DSC3067
200,0268_0260,-1,443,124,319,268/DSC3088,260_260
201,0268_0261,-1,444,119,325,268/DSC3088,261_261
202,0268_0266,1,444,197,247,268/DSC3088,266/DSC3067
203,0268_0267,1,443,291,152,268/DSC3088,267/DSC3077

In [13]:
HQf["are they siblings?"].value_counts()

are they siblings?
 1    102
-1    102
Name: count, dtype: int64

Let's get embeddings for all the photos using InsightFace. As in S. Oscarson's thesis, we'll use buffalo_l. We can also try using buffalo_sc.

In [14]:
!pip install -q onnxruntime insightface

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 85.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 77.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 5.8 MB/s eta 0:00:00
  Building wheel for insightface (pyproject.toml) ... done

In [ ]:
!wget https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_sc.zip && unzip buffalo_sc.zip

--2025-01-13 16:06:54--  https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_sc.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/102057483/90d1326b-1109-4ff7-8a22-609648b543b0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250113T160654Z&X-Amz-Expires=300&X-Amz-Signature=7b2b0d797a564e2015448064e3a79a3e6650a38b09271c25d85db5e1e3e4e908&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbuffalo_sc.zip&response-content-type=application%2Foctet-stream [following]
--2025-01-13 16:06:54--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/102057483/90d1326b-1109-4ff7-8a22-609648b543b0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250113T160654Z&X-Amz-Expires=300&X-Amz-Signature=7b2b0d797a564e2015448064e3a79a3e6650a38b09271c25d85db5e1e3e4e908&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbuffalo_sc.zip&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14969382 (14M) [application/octet-stream]
Saving to: ‘buffalo_sc.zip’

buffalo_sc.zip      100%[===================>]  14.28M  11.2MB/s    in 1.3s

2025-01-13 16:06:57 (11.2 MB/s) - ‘buffalo_sc.zip’ saved [14969382/14969382]

Archive:  buffalo_sc.zip
  inflating: det_500m.onnx
  inflating: w600k_mbf.onnx

In [ ]:
!wget https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip && unzip buffalo_l.zip

--2025-01-13 16:07:20--  https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/102057483/8ae2cf05-2fe7-45cc-addd-2fc11120dcd1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250113T160720Z&X-Amz-Expires=300&X-Amz-Signature=b902896d7ac661109da9f55ebab52f43c86bd126925d2400e28ab754df6cd384&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbuffalo_l.zip&response-content-type=application%2Foctet-stream [following]
--2025-01-13 16:07:21--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/102057483/8ae2cf05-2fe7-45cc-addd-2fc11120dcd1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250113%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250113T160720Z&X-Amz-Expires=300&X-Amz-Signature=b902896d7ac661109da9f55ebab52f43c86bd126925d2400e28ab754df6cd384&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbuffalo_l.zip&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 288621354 (275M) [application/octet-stream]
Saving to: ‘buffalo_l.zip’

buffalo_l.zip       100%[===================>] 275.25M  76.8MB/s    in 3.9s

2025-01-13 16:07:25 (70.5 MB/s) - ‘buffalo_l.zip’ saved [288621354/288621354]

Archive:  buffalo_l.zip
  inflating: genderage.onnx
  inflating: 2d106det.onnx
  inflating: det_10g.onnx
  inflating: 1k3d68.onnx
  inflating: w600k_r50.onnx

In [ ]:
import insightface
from insightface.app.common import Face
from insightface.model_zoo import model_zoo


det_model_path = 'det_10g.onnx'
rec_model_path = 'w600k_r50.onnx'

/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 2.0.0 (you have 1.4.20). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

In [ ]:
det_model = model_zoo.get_model(f'{det_model_path}')
rec_model = model_zoo.get_model(f'{rec_model_path}')

det_model.prepare(ctx_id=0, input_size=(640, 640))

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

Let's set the detection threshold low at the minimum.

In [ ]:
det_model.det_thresh = 0
det_model.det_thresh

0

Padding should be unnecessary in the case of this dataset

In [ ]:
import cv2


##
def get_embedding_from_img_path(img_path):
    rgb_img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
    bboxes, kpss = det_model.detect(rgb_img)
    if bboxes.shape[0] == 0:
        return None
    i = 0
    bbox = bboxes[i, 0:4]
    det_score = bboxes[i, 4]

    kps = None
    if kpss is not None:
        kps = kpss[i]

    face = Face(bbox=bbox, kps=kps, det_score=det_score)
    embedding = rec_model.get(rgb_img, face)
    return embedding

In [ ]:
from IPython.display import Image
Image('/content/SiblingsDB/DBs/HQf/1/_DSC5755_1.jpg')

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
%%time

embedding_1 = get_embedding_from_img_path('/content/SiblingsDB/DBs/HQf/1/_DSC5755_1.jpg')

CPU times: user 2.88 s, sys: 121 ms, total: 3 s
Wall time: 2.97 s

In [16]:
from insightface.app import FaceAnalysis


app = FaceAnalysis(name="buffalo_l")
app.prepare(ctx_id=0, det_size=(640,640))

/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 2.0.0 (you have 1.4.20). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

download_path: /root/.insightface/models/buffalo_l
Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...

100%|██████████| 281857/281857 [00:04<00:00, 63075.64KB/s]
/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)

In [ ]:
app.models

{'landmark_3d_68': <insightface.model_zoo.landmark.Landmark at 0x7f5ce99399f0>,
 'landmark_2d_106': <insightface.model_zoo.landmark.Landmark at 0x7f5ce993b190>,
 'detection': <insightface.model_zoo.retinaface.RetinaFace at 0x7f5ce993a830>,
 'genderage': <insightface.model_zoo.attribute.Attribute at 0x7f5ce993a110>,
 'recognition': <insightface.model_zoo.arcface_onnx.ArcFaceONNX at 0x7f5ce993b4c0>}

In [ ]:
app.det_model

In [ ]:
%%time

image = cv2.imread('/content/SiblingsDB/DBs/HQf/1/_DSC5755_1.jpg')
faces = app.get(image)

CPU times: user 1.07 s, sys: 71.9 ms, total: 1.14 s
Wall time: 1.13 s

In [ ]:
faces[0]["embedding"]

array([ 5.13388515e-02, -7.84490108e-02, -1.36073732e+00, -6.77567482e-01,
        3.59064341e-01,  2.87364215e-01,  6.68166876e-01,  9.33008373e-01,
       -6.23125061e-02,  2.60059983e-01,  1.06175506e+00,  6.94895625e-01,
        6.04595542e-01, -7.71158412e-02,  8.94471407e-02,  2.46778041e-01,
        3.64237517e-01,  1.22254252e+00,  4.97247398e-01, -4.16034192e-01,
       -1.19293666e+00, -1.37759256e+00, -1.53494048e+00, -1.00939967e-01,
        4.72575724e-01,  3.52727890e-01, -3.71741116e-01, -3.29294145e-01,
        2.11902171e-01, -1.06837362e-01, -3.38481843e-01,  9.31102276e-01,
       -3.16066623e-01, -9.78289425e-01, -2.53873050e-01,  1.34043872e+00,
        1.07271338e+00,  2.83096701e-01, -2.56359673e+00,  1.20667863e+00,
        8.69557977e-01,  1.85116649e+00, -6.74823284e-01,  7.54164040e-01,
        4.77364838e-01,  1.88147217e-01, -1.15350235e+00, -3.32998902e-01,
       -1.01001894e+00, -2.21199304e-01, -1.10207701e+00, -6.52375221e-01,
        5.74098945e-01, -5.89950383e-01,  7.40557075e-01, -1.56308937e+00,
       -1.30226886e+00, -2.04257205e-01, -1.52009761e+00, -6.35293663e-01,
       -5.01894772e-01, -1.01451898e+00,  1.38302535e-01,  1.55146813e+00,
        1.23657691e+00,  4.61850911e-01, -1.79578319e-01,  1.36615062e+00,
       -4.88263994e-01,  7.00947106e-01,  3.09858054e-01,  7.77133331e-02,
        6.11780941e-01, -1.44082576e-01, -1.28834891e+00,  1.06912568e-01,
       -2.71298736e-01,  4.87785637e-01, -8.42201829e-01, -6.68879509e-01,
       -1.30683422e-01,  1.90693736e-01, -3.35614085e-02,  7.82038495e-02,
       -1.59666085e+00,  5.02001762e-01, -1.67008078e+00,  3.34501803e-01,
        5.57008028e-01, -8.99084866e-01, -1.20809174e+00, -4.33488667e-01,
        1.49385405e+00, -4.97995436e-01, -7.22757697e-01,  5.35498969e-02,
       -3.68360490e-01,  9.49007511e-01,  2.38854975e-01,  6.30787984e-02,
        6.78038076e-02, -5.77278733e-01, -9.89886165e-01,  1.60865653e+00,
       -2.89340806e+00,  5.96792638e-01, -1.37748218e+00,  4.05889869e-01,
        4.56427723e-01,  1.47292542e+00,  5.88367879e-01, -1.52976549e+00,
       -1.65153313e+00, -1.93502545e-01, -8.54890049e-01, -3.23549360e-01,
        1.38008773e-01, -5.03360391e-01,  5.78428745e-01,  7.16634572e-01,
        9.93628979e-01,  6.46631494e-02, -2.28692383e-01,  4.38293934e-01,
        1.61584929e-01,  1.13636112e+00, -1.35778737e+00,  1.63796663e+00,
       -7.20852375e-01, -2.11570337e-01, -2.14161068e-01,  1.06566417e+00,
        2.51354814e-01, -6.63774371e-01, -1.52211219e-01, -1.94435871e+00,
        2.18045521e+00,  2.63941884e-02,  1.39125586e+00,  8.01874161e-01,
       -1.74603987e+00, -1.46258664e+00,  9.23568130e-01,  1.03516245e+00,
        8.48781943e-01, -2.07857296e-01,  1.03599358e+00, -2.28655887e+00,
       -7.23604202e-01, -1.00730860e+00, -1.84247887e+00,  5.60852066e-02,
        5.77187300e-01, -4.33108687e-01,  5.30379832e-01, -3.12703967e-01,
       -1.79941404e+00,  3.76193076e-01, -7.61100054e-01,  6.12472057e-01,
       -2.79906750e-01,  1.48025489e+00, -3.45297039e-01,  1.34435606e+00,
       -9.17803168e-01, -1.26832604e-01, -1.97714001e-01, -8.55841875e-01,
        2.20871530e-02, -9.20788050e-01,  3.07379961e-01,  7.98135698e-01,
        8.20356727e-01,  2.37568572e-01, -4.07622814e-01,  1.17648304e+00,
       -1.37738740e+00, -3.41080129e-01,  1.07199597e+00,  3.94869059e-01,
        5.62325597e-01,  2.80932283e+00, -1.68457961e+00, -2.13478118e-01,
        2.63733774e-01,  9.00226116e-01,  2.18242455e+00,  5.28431296e-01,
        7.49497414e-01,  4.99030232e-01,  8.46638858e-01, -8.62834454e-01,
       -1.22069895e-01,  1.12728500e+00,  3.34571898e-01,  7.40440428e-01,
        5.18570840e-01,  7.91858256e-01, -1.07528321e-01, -2.05854341e-01,
        4.36097622e-01, -1.84452200e+00,  1.97149682e+00, -8.21841538e-01,
       -9.49886680e-01, -9.22609866e-01,  2.09058851e-01, -9.98917222e-01,
       -6.06235147e-01,  2.78992862e-01,  9.17402625e-01, -3.90897989e-01,
        7.99863040e-01,  1.92587078e-03, -5.10423541e-01,  1.17410481e+00,
        1.53625572e+00, -1.55381143e-01,  2.11816758e-01, -3.18992406e-01,
       -1.58693099e+00,  7.70169377e-01, -1.33511066e-01,  9.11766648e-01,
        2.19040111e-01,  7.48921931e-01, -6.94759130e-01,  1.01563179e+00,
       -9.78244603e-01,  9.90314245e-01,  1.04624045e+00,  2.19173908e+00,
       -2.19067380e-01,  4.21698242e-01, -1.39495790e+00, -3.09177756e-01,
       -2.74829715e-01,  1.70707077e-01,  1.29681087e+00, -1.60193706e+00,
       -3.56253982e-01,  1.52150524e+00, -6.70274556e-01,  5.72862923e-01,
        2.49360144e-01,  1.19360578e+00,  1.30839312e+00, -2.59172767e-01,
       -1.54910535e-02, -5.57388842e-01,  3.47502083e-01,  8.50644052e-01,
       -5.45514464e-01, -2.16669798e-01,  3.93553972e-01,  1.12831140e+00,
        4.20515984e-01,  2.27515176e-01,  2.19141912e+00,  1.91605294e+00,
        1.20853335e-02, -1.05796409e+00, -1.63256693e+00, -2.32989624e-01,
        6.59447163e-03,  1.04299092e+00,  1.31657946e+00, -1.30629182e-01,
       -7.14675367e-01,  7.03658462e-01,  2.12901145e-01,  8.42516199e-02,
        1.88835815e-01,  2.16330695e+00,  4.45682883e-01, -8.48197997e-01,
        9.50577408e-02, -8.94031107e-01, -1.80684209e-01,  4.13187563e-01,
       -8.20181191e-01,  3.56976807e-01,  1.62587211e-01,  4.14099932e-01,
       -1.20650506e+00,  1.61711133e+00, -1.31230104e+00,  6.10614061e-01,
        1.50725007e+00,  8.03138092e-02, -1.37630135e-01, -9.80488658e-01,
        7.24574476e-02,  1.06989138e-01, -3.28665301e-02, -1.03798854e+00,
        2.48137736e+00,  1.38148212e+00, -9.39294100e-02, -6.46493196e-01,
        5.10864496e-01,  4.44670260e-01,  1.19960403e+00,  5.14535666e-01,
       -7.23999441e-01, -3.57551605e-01, -3.49201143e-01,  2.07757664e+00,
       -9.54497695e-01, -7.11285710e-01,  1.10875793e-01, -4.89086032e-01,
        9.62291837e-01,  4.96246427e-01, -4.22326237e-01,  1.05978584e+00,
        7.80126810e-01,  5.75462222e-01, -3.22263062e-01, -2.04150438e-01,
       -2.21473292e-01, -2.44098529e-01,  8.70480299e-01, -1.94845140e-01,
        3.93302441e-01,  1.96551192e+00,  5.12547314e-01, -1.50995350e+00,
       -3.72695029e-01, -8.69695187e-01, -2.20296346e-02, -5.81274748e-01,
        8.25823128e-01,  3.48141611e-01, -7.91842163e-01, -6.50211096e-01,
       -4.84290719e-01, -7.90030241e-01, -6.54638112e-01,  8.03923681e-02,
        1.05594635e+00,  9.64830160e-01, -6.71556354e-01, -1.96092784e+00,
       -5.28317504e-02, -3.91038507e-01, -4.23050255e-01,  1.01562738e-02,
       -1.32181156e+00, -7.07313061e-01,  1.45116401e+00,  1.18328679e+00,
       -9.71971452e-03,  1.93314210e-01,  1.04685080e+00,  1.01292312e-01,
       -4.58857059e-01, -1.83643475e-01, -9.68053639e-01,  6.38080418e-01,
        7.51527131e-01,  6.67853236e-01, -4.05041724e-01, -4.52098846e-01,
        3.77545580e-02, -1.22906998e-01,  6.04626238e-01,  3.29887629e-01,
        7.34285712e-01,  1.63942957e+00, -6.20433271e-01,  4.53680456e-02,
       -6.84381902e-01,  5.22729039e-01,  1.43100631e+00, -1.70769262e+00,
       -4.31661576e-01,  1.89733893e-01,  5.42863011e-01, -1.96680975e+00,
        3.13867122e-01,  9.36347246e-01, -4.29555476e-01,  8.36223781e-01,
       -2.12198067e+00,  1.07820427e+00, -6.40984774e-01,  4.26049680e-01,
       -6.57142103e-01, -6.54591322e-01, -1.06546664e+00,  1.04457259e+00,
        5.60191333e-01, -1.26276290e+00, -5.66300809e-01,  1.52618861e+00,
        6.76856995e-01, -8.38629603e-01, -2.81088233e-01,  4.07969773e-01,
        2.04273790e-01,  1.93932980e-01, -2.32571766e-01, -1.26265001e+00,
       -4.67982233e-01,  1.03037667e+00,  8.85114193e-01, -8.37475285e-02,
       -3.10958296e-01,  1.24699429e-01, -3.39778870e-01, -1.24687922e+00,
        8.12912583e-01,  2.60791004e-01,  1.37816679e+00, -1.66086304e+00,
       -2.20629051e-02, -5.01433611e-01, -3.95683229e-01,  5.52595735e-01,
        1.59803778e-01,  2.13321254e-01, -7.76484489e-01,  1.80534005e-01,
       -1.02515185e+00,  1.16255271e+00, -4.31569546e-01,  1.10518977e-01,
        3.04337353e-01, -7.05823243e-01, -1.05890703e+00,  1.36566710e+00,
        1.22056127e+00,  1.20870781e+00, -5.51633775e-01,  1.30980313e+00,
        9.18201149e-01, -6.80964947e-01, -7.39398718e-01, -1.21793532e+00,
        5.85563183e-01,  1.56607941e-01, -1.83698833e-01, -5.91580570e-01,
        1.71543121e-01, -1.01119792e+00, -1.34016001e+00, -4.19890404e-01,
       -1.10956900e-01,  2.52431929e-01,  3.04521203e-01, -1.41642734e-01,
       -6.45883024e-01, -9.36359465e-02, -1.03718626e+00, -1.36355013e-01,
       -3.05003881e-01, -1.68686032e+00,  1.42118168e+00,  6.96669340e-01,
       -4.71093655e-01, -6.30406439e-01, -4.57778096e-01,  3.36048692e-01,
        2.22242332e+00,  1.45853734e+00,  8.75869155e-01, -7.44295299e-01,
        1.34765595e-01, -1.43305814e+00,  1.04905677e+00, -4.44045037e-01,
        1.07414341e+00,  8.62695932e-01,  7.25608110e-01,  1.08033633e+00,
        5.44003904e-01,  7.12305129e-01,  7.90450215e-01,  7.74529517e-01,
        2.30283785e+00, -8.18374336e-01,  1.71090007e+00, -1.16437232e+00,
       -8.83558542e-02, -1.15260124e+00, -4.42103744e-02,  6.71989858e-01,
        9.16016459e-01, -1.77061439e+00, -1.95020652e+00, -9.67004180e-01,
        1.44173086e-01,  7.20748067e-01, -7.93422461e-01, -1.46722510e-01,
        7.78647125e-01, -1.53668344e+00, -4.75776941e-01, -1.37519717e+00,
       -7.32194781e-01,  4.21813577e-01, -5.87348282e-01, -5.01572311e-01,
        9.81822491e-01,  1.13050926e+00,  2.11578757e-01, -2.49795413e+00,
        6.16210759e-01, -1.16576180e-02,  7.72059023e-01,  1.56085587e+00],
      dtype=float32)

In [ ]:
import scipy

scipy.spatial.distance.cosine(embedding_1, faces[0]["embedding"])

0.0704313494140838

In [19]:
paths = []
for dataset in ['HQf', 'HQfp', 'HQfps', 'LQf']:
  path = f'/content/SiblingsDB/DBs/{dataset}'
  if dataset == 'LQf':
    for file in os.listdir(path):
      if ".jpg" in file:
        paths.append(os.path.join(path, file))
  else:
    for folder in os.listdir(path):
      for file in os.listdir(os.path.join(path, folder)):
        if ".jpg" in file:
          paths.append(os.path.join(path, folder, file))
paths

['/content/SiblingsDB/DBs/HQf/221/_DSC2256.jpg',
 '/content/SiblingsDB/DBs/HQf/194/_DSC0812.jpg',
 '/content/SiblingsDB/DBs/HQf/90/_DSC0091.jpg',
 '/content/SiblingsDB/DBs/HQf/19/_DSC5859.jpg',
 '/content/SiblingsDB/DBs/HQf/52/_DSC5979.jpg',
 '/content/SiblingsDB/DBs/HQf/67/_DSC9933.jpg',
 '/content/SiblingsDB/DBs/HQf/88/_DSC0067.jpg',
 '/content/SiblingsDB/DBs/HQf/176/176.jpg',
 '/content/SiblingsDB/DBs/HQf/104/_DSC0181.jpg',
 '/content/SiblingsDB/DBs/HQf/185/_DSC0743.jpg',
 '/content/SiblingsDB/DBs/HQf/229/_DSC2898.jpg',
 '/content/SiblingsDB/DBs/HQf/220/_DSC2248.jpg',
 '/content/SiblingsDB/DBs/HQf/227/_DSC2305.jpg',
 '/content/SiblingsDB/DBs/HQf/141/141.jpg',
 '/content/SiblingsDB/DBs/HQf/1/_DSC5755_1.jpg',
 '/content/SiblingsDB/DBs/HQf/123/_DSC0302.jpg',
 '/content/SiblingsDB/DBs/HQf/255/_DSC3048.jpg',
 '/content/SiblingsDB/DBs/HQf/231/231.jpg',
 '/content/SiblingsDB/DBs/HQf/77/_DSC9993.jpg',
 '/content/SiblingsDB/DBs/HQf/45/_DSC5955.jpg',
 '/content/SiblingsDB/DBs/HQf/39/_DSC5924.jpg',
 '/content/SiblingsDB/DBs/HQf/61/_DSC6001.jpg',
 '/content/SiblingsDB/DBs/HQf/17/_DSC5854.jpg',
 '/content/SiblingsDB/DBs/HQf/167/_DSC0666.jpg',
 '/content/SiblingsDB/DBs/HQf/62/_DSC9913.jpg',
 '/content/SiblingsDB/DBs/HQf/84/_DSC0034.jpg',
 '/content/SiblingsDB/DBs/HQf/181/_DSC0714.jpg',
 '/content/SiblingsDB/DBs/HQf/106/_DSC0195.jpg',
 '/content/SiblingsDB/DBs/HQf/186/_DSC0751.jpg',
 '/content/SiblingsDB/DBs/HQf/82/_DSC0019.jpg',
 '/content/SiblingsDB/DBs/HQf/149/_DSC0564.jpg',
 '/content/SiblingsDB/DBs/HQf/115/_DSC0266.jpg',
 '/content/SiblingsDB/DBs/HQf/251/_DSC3023.jpg',
 '/content/SiblingsDB/DBs/HQf/163/_DSC0633.jpg',
 '/content/SiblingsDB/DBs/HQf/164/_DSC0641.jpg',
 '/content/SiblingsDB/DBs/HQf/122/_DSC0294.jpg',
 '/content/SiblingsDB/DBs/HQf/263/263.jpg',
 '/content/SiblingsDB/DBs/HQf/15/_DSC5843.jpg',
 '/content/SiblingsDB/DBs/HQf/31/_DSC5911.jpg',
 '/content/SiblingsDB/DBs/HQf/201/_DSC0852.jpg',
 '/content/SiblingsDB/DBs/HQf/230/230.jpg',
 '/content/SiblingsDB/DBs/HQf/72/_DSC9983.jpg',
 '/content/SiblingsDB/DBs/HQf/107/_DSC0204.jpg',
 '/content/SiblingsDB/DBs/HQf/95/_DSC0105.jpg',
 '/content/SiblingsDB/DBs/HQf/113/_DSC0250.jpg',
 '/content/SiblingsDB/DBs/HQf/205/_DSC0875.jpg',
 '/content/SiblingsDB/DBs/HQf/154/_DSC0598.jpg',
 '/content/SiblingsDB/DBs/HQf/191/_DSC0791.jpg',
 '/content/SiblingsDB/DBs/HQf/63/_DSC9905.jpg',
 '/content/SiblingsDB/DBs/HQf/248/_DSC2992.jpg',
 '/content/SiblingsDB/DBs/HQf/59/_DSC6012.jpg',
 '/content/SiblingsDB/DBs/HQf/204/_DSC0868.jpg',
 '/content/SiblingsDB/DBs/HQf/112/_DSC0241.jpg',
 '/content/SiblingsDB/DBs/HQf/86/_DSC0058.jpg',
 '/content/SiblingsDB/DBs/HQf/184/_DSC0736.jpg',
 '/content/SiblingsDB/DBs/HQf/219/_DSC2232.jpg',
 '/content/SiblingsDB/DBs/HQf/160/160.jpg',
 '/content/SiblingsDB/DBs/HQf/261/261.jpg',
 '/content/SiblingsDB/DBs/HQf/213/_DSC2184.jpg',
 '/content/SiblingsDB/DBs/HQf/66/_DSC9920.jpg',
 '/content/SiblingsDB/DBs/HQf/47/047.jpg',
 '/content/SiblingsDB/DBs/HQf/190/_DSC0784.jpg',
 '/content/SiblingsDB/DBs/HQf/199/_DSC0829.jpg',
 '/content/SiblingsDB/DBs/HQf/249/_DSC3002.jpg',
 '/content/SiblingsDB/DBs/HQf/158/158.jpg',
 '/content/SiblingsDB/DBs/HQf/161/_DSC0617.jpg',
 '/content/SiblingsDB/DBs/HQf/85/_DSC0041.jpg',
 '/content/SiblingsDB/DBs/HQf/247/_DSC2966.jpg',
 '/content/SiblingsDB/DBs/HQf/210/_DSC2164.jpg',
 '/content/SiblingsDB/DBs/HQf/87/_DSC0051.jpg',
 '/content/SiblingsDB/DBs/HQf/228/_DSC2891.jpg',
 '/content/SiblingsDB/DBs/HQf/50/_DSC5961.jpg',
 '/content/SiblingsDB/DBs/HQf/217/_DSC2217.jpg',
 '/content/SiblingsDB/DBs/HQf/109/_DSC0215.jpg',
 '/content/SiblingsDB/DBs/HQf/182/_DSC0720.jpg',
 '/content/SiblingsDB/DBs/HQf/127/_DSC0355.jpg',
 '/content/SiblingsDB/DBs/HQf/23/_DSC5872.jpg',
 '/content/SiblingsDB/DBs/HQf/83/_DSC0026.jpg',
 '/content/SiblingsDB/DBs/HQf/216/_DSC2209.jpg',
 '/content/SiblingsDB/DBs/HQf/98/_DSC0138.jpg',
 '/content/SiblingsDB/DBs/HQf/16/_DSC5850.jpg',
 '/content/SiblingsDB/DBs/HQf/226/_DSC2297.jpg',
 '/content/SiblingsDB/DBs/HQf/27/_DSC5885.jpg',
 '/content/SiblingsDB/DBs/HQf/165/_DSC0652.jpg',
 '/content/SiblingsDB/DBs/HQf/246/_DSC2982.jpg',
 '/content/SiblingsDB/DBs/HQf/8/_DSC5774.jpg',
 '/content/SiblingsDB/DBs/HQf/32/_DSC5905.jpg',
 '/content/SiblingsDB/DBs/HQf/114/_DSC0257.jpg',
 '/content/SiblingsDB/DBs/HQf/74/074.jpg',
 '/content/SiblingsDB/DBs/HQf/111/_DSC0234.jpg',
 '/content/SiblingsDB/DBs/HQf/137/_DSC0441.jpg',
 '/content/SiblingsDB/DBs/HQf/51/_DSC5971.jpg',
 '/content/SiblingsDB/DBs/HQf/99/_DSC0145.jpg',
 '/content/SiblingsDB/DBs/HQf/28/_DSC5881.jpg',
 '/content/SiblingsDB/DBs/HQf/155/_DSC0609.jpg',
 '/content/SiblingsDB/DBs/HQf/266/_DSC3067.jpg',
 '/content/SiblingsDB/DBs/HQf/81/_DSC0011.jpg',
 '/content/SiblingsDB/DBs/HQf/100/_DSC0152.jpg',
 '/content/SiblingsDB/DBs/HQf/192/_DSC0801.jpg',
 '/content/SiblingsDB/DBs/HQf/209/_DSC0898.jpg',
 '/content/SiblingsDB/DBs/HQf/211/_DSC2170.jpg',
 '/content/SiblingsDB/DBs/HQf/146/_DSC0550.jpg',
 '/content/SiblingsDB/DBs/HQf/42/_DSC5928.jpg',
 '/content/SiblingsDB/DBs/HQf/177/_DSC0707.jpg',
 '/content/SiblingsDB/DBs/HQf/195/195.jpg',
 '/content/SiblingsDB/DBs/HQf/207/_DSC0882.jpg',
 '/content/SiblingsDB/DBs/HQf/96/_DSC0121.jpg',
 '/content/SiblingsDB/DBs/HQf/150/_DSC0572.jpg',
 '/content/SiblingsDB/DBs/HQf/143/_DSC0527.jpg',
 '/content/SiblingsDB/DBs/HQf/268/_DSC3088.jpg',
 '/content/SiblingsDB/DBs/HQf/13/_DSC5818.jpg',
 '/content/SiblingsDB/DBs/HQf/183/_DSC0729.jpg',
 '/content/SiblingsDB/DBs/HQf/53/_DSC5983.jpg',
 '/content/SiblingsDB/DBs/HQf/240/_DSC2946.jpg',
 '/content/SiblingsDB/DBs/HQf/43/_DSC5942.jpg',
 '/content/SiblingsDB/DBs/HQf/237/_DSC2922.jpg',
 '/content/SiblingsDB/DBs/HQf/21/021.jpg',
 '/content/SiblingsDB/DBs/HQf/119/_DSC0284.jpg',
 '/content/SiblingsDB/DBs/HQf/166/_DSC0657.jpg',
 '/content/SiblingsDB/DBs/HQf/144/_DSC0534.jpg',
 '/content/SiblingsDB/DBs/HQf/18/018.jpg',
 '/content/SiblingsDB/DBs/HQf/212/_DSC2175.jpg',
 '/content/SiblingsDB/DBs/HQf/224/_DSC2281.jpg',
 '/content/SiblingsDB/DBs/HQf/44/_DSC5948.jpg',
 '/content/SiblingsDB/DBs/HQf/178/178.jpg',
 '/content/SiblingsDB/DBs/HQf/94/_DSC0114.jpg',
 '/content/SiblingsDB/DBs/HQf/128/_DSC0362.jpg',
 '/content/SiblingsDB/DBs/HQf/193/_DSC0806.jpg',
 '/content/SiblingsDB/DBs/HQf/35/_DSC5896.jpg',
 '/content/SiblingsDB/DBs/HQf/89/_DSC0083.jpg',
 '/content/SiblingsDB/DBs/HQf/129/_DSC0369.jpg',
 '/content/SiblingsDB/DBs/HQf/14/_DSC5826.jpg',
 '/content/SiblingsDB/DBs/HQf/49/_DSC5966.jpg',
 '/content/SiblingsDB/DBs/HQf/202/_DSC0859.jpg',
 '/content/SiblingsDB/DBs/HQf/133/_DSC0401.jpg',
 '/content/SiblingsDB/DBs/HQf/5/_DSC5763.jpg',
 '/content/SiblingsDB/DBs/HQf/36/_DSC5900.jpg',
 '/content/SiblingsDB/DBs/HQf/40/_DSC5919.jpg',
 '/content/SiblingsDB/DBs/HQf/151/_DSC0579.jpg',
 '/content/SiblingsDB/DBs/HQf/108/_DSC0211.jpg',
 '/content/SiblingsDB/DBs/HQf/168/DSCK0014.jpg',
 '/content/SiblingsDB/DBs/HQf/73/_DSC9974.jpg',
 '/content/SiblingsDB/DBs/HQf/208/_DSC0888.jpg',
 '/content/SiblingsDB/DBs/HQf/218/_DSC2223.jpg',
 '/content/SiblingsDB/DBs/HQf/58/_DSC5835.jpg',
 '/content/SiblingsDB/DBs/HQf/6/_DSC5760.jpg',
 '/content/SiblingsDB/DBs/HQf/41/_DSC5937.jpg',
 '/content/SiblingsDB/DBs/HQf/60/_DSC6005.jpg',
 '/content/SiblingsDB/DBs/HQf/24/_DSC5863.jpg',
 '/content/SiblingsDB/DBs/HQf/254/_DSC3036.jpg',
 '/content/SiblingsDB/DBs/HQf/148/_DSC0557.jpg',
 '/content/SiblingsDB/DBs/HQf/9/_DSC5792.jpg',
 '/content/SiblingsDB/DBs/HQf/118/_DSC0274.jpg',
 '/content/SiblingsDB/DBs/HQf/256/_DSC2975.jpg',
 '/content/SiblingsDB/DBs/HQf/173/_DSC0682.jpg',
 '/content/SiblingsDB/DBs/HQf/124/_DSC0309.jpg',
 '/content/SiblingsDB/DBs/HQf/145/_DSC0542.jpg',
 '/content/SiblingsDB/DBs/HQf/236/_DSC2913.jpg',
 '/content/SiblingsDB/DBs/HQf/80/_DSC0002.jpg',
 '/content/SiblingsDB/DBs/HQf/3/_DSC5751.jpg',
 '/content/SiblingsDB/DBs/HQf/126/_DSC0346.jpg',
 '/content/SiblingsDB/DBs/HQf/267/_DSC3077.jpg',
 '/content/SiblingsDB/DBs/HQf/138/_DSC0452.jpg',
 '/content/SiblingsDB/DBs/HQf/260/260.jpg',
 '/content/SiblingsDB/DBs/HQf/57/_DSC5832.jpg',
 '/content/SiblingsDB/DBs/HQf/250/_DSC3013.jpg',
 '/content/SiblingsDB/DBs/HQf/97/_DSC0130.jpg',
 '/content/SiblingsDB/DBs/HQf/198/_DSC0822.jpg',
 '/content/SiblingsDB/DBs/HQf/110/_DSC0225.jpg',
 '/content/SiblingsDB/DBs/HQf/162/_DSC0625.jpg',
 '/content/SiblingsDB/DBs/HQf/125/_DSC0320.jpg',
 '/content/SiblingsDB/DBs/HQf/130/_DSC0379.jpg',
 '/content/SiblingsDB/DBs/HQf/91/_DSC0099.jpg',
 '/content/SiblingsDB/DBs/HQf/10/_DSC5804.jpg',
 '/content/SiblingsDB/DBs/HQf/7/_DSC5769.jpg',
 '/content/SiblingsDB/DBs/HQf/54/_DSC5996.jpg',
 '/content/SiblingsDB/DBs/HQf/262/_DSC3056.jpg',
 '/content/SiblingsDB/DBs/HQf/152/_DSC0585.jpg',
 '/content/SiblingsDB/DBs/HQf/259/259.jpg',
 '/content/SiblingsDB/DBs/HQf/153/_DSC0592.jpg',
 '/content/SiblingsDB/DBs/HQfp/221/_DSC2256.jpg',
 '/content/SiblingsDB/DBs/HQfp/221/_DSC2260.jpg',
 '/content/SiblingsDB/DBs/HQfp/194/_DSC0812.jpg',
 '/content/SiblingsDB/DBs/HQfp/194/_DSC0816.jpg',
 '/content/SiblingsDB/DBs/HQfp/90/_DSC0094.jpg',
 '/content/SiblingsDB/DBs/HQfp/90/_DSC0091.jpg',
 '/content/SiblingsDB/DBs/HQfp/19/_DSC5862.jpg',
 '/content/SiblingsDB/DBs/HQfp/19/_DSC5859.jpg',
 '/content/SiblingsDB/DBs/HQfp/52/_DSC5981.jpg',
 '/content/SiblingsDB/DBs/HQfp/52/_DSC5979.jpg',
 '/content/SiblingsDB/DBs/HQfp/67/_DSC9933.jpg',
 '/content/SiblingsDB/DBs/HQfp/67/_DSC9938.jpg',
 '/content/SiblingsDB/DBs/HQfp/88/_DSC0067.jpg',
 '/content/SiblingsDB/DBs/HQfp/88/_DSC0072.jpg',
 '/content/SiblingsDB/DBs/HQfp/104/_DSC0181.jpg',
 '/content/SiblingsDB/DBs/HQfp/104/_DSC0185.jpg',
 '/content/SiblingsDB/DBs/HQfp/185/_DSC0743.jpg',
 '/content/SiblingsDB/DBs/HQfp/185/_DSC0746.jpg',
 '/content/SiblingsDB/DBs/HQfp/229/_DSC2903.jpg',
 '/content/SiblingsDB/DBs/HQfp/229/_DSC2898.jpg',
 '/content/SiblingsDB/DBs/HQfp/220/_DSC2248.jpg',
 '/content/SiblingsDB/DBs/HQfp/220/_DSC2252.jpg',
 '/content/SiblingsDB/DBs/HQfp/227/_DSC2309.jpg',
 '/content/SiblingsDB/DBs/HQfp/227/_DSC2305.jpg',
 '/content/SiblingsDB/DBs/HQfp/1/_DSC5758_1.jpg',
 '/content/SiblingsDB/DBs/HQfp/1/_DSC5755_1.jpg',
 '/content/SiblingsDB/DBs/HQfp/123/_DSC0306.jpg',
 '/content/SiblingsDB/DBs/HQfp/123/_DSC0302.jpg',
 '/content/SiblingsDB/DBs/HQfp/255/_DSC3049.jpg',
 '/content/SiblingsDB/DBs/HQfp/255/_DSC3048.jpg',
 '/content/SiblingsDB/DBs/HQfp/77/_DSC9998.jpg',
 '/content/SiblingsDB/DBs/HQfp/77/_DSC9993.jpg',
 '/content/SiblingsDB/DBs/HQfp/45/_DSC5958.jpg',
 '/content/SiblingsDB/DBs/HQfp/45/_DSC5955.jpg',
 '/content/SiblingsDB/DBs/HQfp/39/_DSC5927.jpg',
 '/content/SiblingsDB/DBs/HQfp/39/_DSC5924.jpg',
 '/content/SiblingsDB/DBs/HQfp/61/_DSC6004.jpg',
 '/content/SiblingsDB/DBs/HQfp/61/_DSC6001.jpg',
 '/content/SiblingsDB/DBs/HQfp/17/_DSC5855.jpg',
 '/content/SiblingsDB/DBs/HQfp/17/_DSC5854.jpg',
 '/content/SiblingsDB/DBs/HQfp/167/_DSC0669.jpg',
 '/content/SiblingsDB/DBs/HQfp/167/_DSC0666.jpg',
 '/content/SiblingsDB/DBs/HQfp/62/_DSC9913.jpg',
 '/content/SiblingsDB/DBs/HQfp/62/_DSC9917.jpg',
 '/content/SiblingsDB/DBs/HQfp/84/_DSC0034.jpg',
 '/content/SiblingsDB/DBs/HQfp/84/_DSC0037.jpg',
 '/content/SiblingsDB/DBs/HQfp/181/_DSC0717.jpg',
 '/content/SiblingsDB/DBs/HQfp/181/_DSC0714.jpg',
 '/content/SiblingsDB/DBs/HQfp/106/_DSC0195.jpg',
 '/content/SiblingsDB/DBs/HQfp/106/_DSC0199.jpg',
 '/content/SiblingsDB/DBs/HQfp/186/_DSC0751.jpg',
 '/content/SiblingsDB/DBs/HQfp/186/_DSC0754.jpg',
 '/content/SiblingsDB/DBs/HQfp/82/_DSC0019.jpg',
 '/content/SiblingsDB/DBs/HQfp/82/_DSC0022.jpg',
 '/content/SiblingsDB/DBs/HQfp/149/_DSC0568.jpg',
 '/content/SiblingsDB/DBs/HQfp/149/_DSC0564.jpg',
 '/content/SiblingsDB/DBs/HQfp/115/_DSC0266.jpg',
 '/content/SiblingsDB/DBs/HQfp/115/_DSC0269.jpg',
 '/content/SiblingsDB/DBs/HQfp/251/_DSC3029.jpg',
 '/content/SiblingsDB/DBs/HQfp/251/_DSC3023.jpg',
 '/content/SiblingsDB/DBs/HQfp/163/_DSC0633.jpg',
 '/content/SiblingsDB/DBs/HQfp/163/_DSC0637.jpg',
 '/content/SiblingsDB/DBs/HQfp/164/_DSC0641.jpg',
 '/content/SiblingsDB/DBs/HQfp/164/_DSC0646.jpg',
 '/content/SiblingsDB/DBs/HQfp/122/_DSC0294.jpg',
 '/content/SiblingsDB/DBs/HQfp/122/_DSC0298.jpg',
 '/content/SiblingsDB/DBs/HQfp/15/_DSC5843.jpg',
 '/content/SiblingsDB/DBs/HQfp/15/_DSC5846.jpg',
 '/content/SiblingsDB/DBs/HQfp/31/_DSC5913.jpg',
 '/content/SiblingsDB/DBs/HQfp/31/_DSC5911.jpg',
 '/content/SiblingsDB/DBs/HQfp/201/_DSC0852.jpg',
 '/content/SiblingsDB/DBs/HQfp/201/_DSC0856.jpg',
 '/content/SiblingsDB/DBs/HQfp/72/_DSC9988.jpg',
 '/content/SiblingsDB/DBs/HQfp/72/_DSC9983.jpg',
 '/content/SiblingsDB/DBs/HQfp/107/_DSC0204.jpg',
 '/content/SiblingsDB/DBs/HQfp/107/_DSC0207.jpg',
 '/content/SiblingsDB/DBs/HQfp/95/_DSC0108.jpg',
 '/content/SiblingsDB/DBs/HQfp/95/_DSC0105.jpg',
 '/content/SiblingsDB/DBs/HQfp/113/_DSC0250.jpg',
 '/content/SiblingsDB/DBs/HQfp/113/_DSC0253.jpg',
 '/content/SiblingsDB/DBs/HQfp/205/_DSC0878.jpg',
 '/content/SiblingsDB/DBs/HQfp/205/_DSC0875.jpg',
 '/content/SiblingsDB/DBs/HQfp/154/_DSC0605.jpg',
 '/content/SiblingsDB/DBs/HQfp/154/_DSC0598.jpg',
 '/content/SiblingsDB/DBs/HQfp/191/_DSC0791.jpg',
 '/content/SiblingsDB/DBs/HQfp/191/_DSC0795.jpg',
 '/content/SiblingsDB/DBs/HQfp/63/_DSC9905.jpg',
 '/content/SiblingsDB/DBs/HQfp/63/_DSC9909.jpg',
 '/content/SiblingsDB/DBs/HQfp/248/_DSC2999.jpg',
 '/content/SiblingsDB/DBs/HQfp/248/_DSC2992.jpg',
 '/content/SiblingsDB/DBs/HQfp/59/_DSC6016.jpg',
 '/content/SiblingsDB/DBs/HQfp/59/_DSC6012.jpg',
 '/content/SiblingsDB/DBs/HQfp/204/_DSC0870.jpg',
 '/content/SiblingsDB/DBs/HQfp/204/_DSC0868.jpg',
 '/content/SiblingsDB/DBs/HQfp/112/_DSC0241.jpg',
 '/content/SiblingsDB/DBs/HQfp/112/_DSC0245.jpg',
 '/content/SiblingsDB/DBs/HQfp/86/_DSC0058.jpg',
 '/content/SiblingsDB/DBs/HQfp/86/_DSC0062.jpg',
 '/content/SiblingsDB/DBs/HQfp/184/_DSC0740.jpg',
 '/content/SiblingsDB/DBs/HQfp/184/_DSC0736.jpg',
 '/content/SiblingsDB/DBs/HQfp/219/_DSC2232.jpg',
 '/content/SiblingsDB/DBs/HQfp/219/_DSC2236.jpg',
 '/content/SiblingsDB/DBs/HQfp/213/_DSC2187.jpg',
 '/content/SiblingsDB/DBs/HQfp/213/_DSC2184.jpg',
 '/content/SiblingsDB/DBs/HQfp/66/_DSC9926.jpg',
 '/content/SiblingsDB/DBs/HQfp/66/_DSC9920.jpg',
 '/content/SiblingsDB/DBs/HQfp/190/_DSC0787.jpg',
 '/content/SiblingsDB/DBs/HQfp/190/_DSC0784.jpg',
 '/content/SiblingsDB/DBs/HQfp/199/_DSC0829.jpg',
 '/content/SiblingsDB/DBs/HQfp/199/_DSC0832.jpg',
 '/content/SiblingsDB/DBs/HQfp/249/_DSC3009.jpg',
 '/content/SiblingsDB/DBs/HQfp/249/_DSC3002.jpg',
 '/content/SiblingsDB/DBs/HQfp/161/_DSC0617.jpg',
 '/content/SiblingsDB/DBs/HQfp/161/_DSC0623.jpg',
 '/content/SiblingsDB/DBs/HQfp/85/_DSC0045.jpg',
 '/content/SiblingsDB/DBs/HQfp/85/_DSC0041.jpg',
 '/content/SiblingsDB/DBs/HQfp/247/_DSC2966.jpg',
 '/content/SiblingsDB/DBs/HQfp/247/_DSC2970.jpg',
 '/content/SiblingsDB/DBs/HQfp/210/_DSC2166.jpg',
 '/content/SiblingsDB/DBs/HQfp/210/_DSC2164.jpg',
 '/content/SiblingsDB/DBs/HQfp/87/_DSC0054.jpg',
 '/content/SiblingsDB/DBs/HQfp/87/_DSC0051.jpg',
 '/content/SiblingsDB/DBs/HQfp/228/_DSC2895.jpg',
 '/content/SiblingsDB/DBs/HQfp/228/_DSC2891.jpg',
 '/content/SiblingsDB/DBs/HQfp/50/_DSC5961.jpg',
 '/content/SiblingsDB/DBs/HQfp/50/_DSC5963.jpg',
 '/content/SiblingsDB/DBs/HQfp/217/_DSC2217.jpg',
 '/content/SiblingsDB/DBs/HQfp/217/_DSC2219.jpg',
 '/content/SiblingsDB/DBs/HQfp/109/_DSC0215.jpg',
 '/content/SiblingsDB/DBs/HQfp/109/_DSC0222.jpg',
 '/content/SiblingsDB/DBs/HQfp/182/_DSC0725.jpg',
 '/content/SiblingsDB/DBs/HQfp/182/_DSC0720.jpg',
 '/content/SiblingsDB/DBs/HQfp/127/_DSC0355.jpg',
 '/content/SiblingsDB/DBs/HQfp/127/_DSC0359.jpg',
 '/content/SiblingsDB/DBs/HQfp/23/_DSC5872.jpg',
 '/content/SiblingsDB/DBs/HQfp/23/_DSC5874.jpg',
 '/content/SiblingsDB/DBs/HQfp/83/_DSC0026.jpg',
 '/content/SiblingsDB/DBs/HQfp/83/_DSC0031.jpg',
 '/content/SiblingsDB/DBs/HQfp/216/_DSC2211.jpg',
 '/content/SiblingsDB/DBs/HQfp/216/_DSC2209.jpg',
 '/content/SiblingsDB/DBs/HQfp/98/_DSC0138.jpg',
 '/content/SiblingsDB/DBs/HQfp/98/_DSC0141.jpg',
 '/content/SiblingsDB/DBs/HQfp/16/_DSC5850.jpg',
 '/content/SiblingsDB/DBs/HQfp/16/_DSC5852.jpg',
 '/content/SiblingsDB/DBs/HQfp/226/_DSC2297.jpg',
 '/content/SiblingsDB/DBs/HQfp/226/_DSC2300.jpg',
 '/content/SiblingsDB/DBs/HQfp/27/_DSC5885.jpg',
 '/content/SiblingsDB/DBs/HQfp/27/_DSC5887.jpg',
 '/content/SiblingsDB/DBs/HQfp/165/_DSC0652.jpg',
 '/content/SiblingsDB/DBs/HQfp/165/_DSC0654.jpg',
 '/content/SiblingsDB/DBs/HQfp/246/_DSC2982.jpg',
 '/content/SiblingsDB/DBs/HQfp/246/_DSC2986.jpg',
 '/content/SiblingsDB/DBs/HQfp/8/_DSC5775.jpg',
 '/content/SiblingsDB/DBs/HQfp/8/_DSC5774.jpg',
 '/content/SiblingsDB/DBs/HQfp/32/_DSC5905.jpg',
 '/content/SiblingsDB/DBs/HQfp/32/_DSC5907.jpg',
 '/content/SiblingsDB/DBs/HQfp/114/_DSC0257.jpg',
 '/content/SiblingsDB/DBs/HQfp/114/_DSC0261.jpg',
 '/content/SiblingsDB/DBs/HQfp/111/_DSC0238.jpg',
 '/content/SiblingsDB/DBs/HQfp/111/_DSC0234.jpg',
 '/content/SiblingsDB/DBs/HQfp/137/_DSC0441.jpg',
 '/content/SiblingsDB/DBs/HQfp/137/_DSC0449.jpg',
 '/content/SiblingsDB/DBs/HQfp/51/_DSC5976.jpg',
 '/content/SiblingsDB/DBs/HQfp/51/_DSC5971.jpg',
 '/content/SiblingsDB/DBs/HQfp/99/_DSC0145.jpg',
 '/content/SiblingsDB/DBs/HQfp/99/_DSC0149.jpg',
 '/content/SiblingsDB/DBs/HQfp/28/_DSC5881.jpg',
 '/content/SiblingsDB/DBs/HQfp/28/_DSC5883.jpg',
 '/content/SiblingsDB/DBs/HQfp/155/_DSC0612.jpg',
 '/content/SiblingsDB/DBs/HQfp/155/_DSC0609.jpg',
 '/content/SiblingsDB/DBs/HQfp/266/_DSC3067.jpg',
 '/content/SiblingsDB/DBs/HQfp/266/_DSC3069.jpg',
 '/content/SiblingsDB/DBs/HQfp/81/_DSC0015.jpg',
 '/content/SiblingsDB/DBs/HQfp/81/_DSC0011.jpg',
 '/content/SiblingsDB/DBs/HQfp/100/_DSC0152.jpg',
 '/content/SiblingsDB/DBs/HQfp/100/_DSC0156.jpg',
 '/content/SiblingsDB/DBs/HQfp/192/_DSC0803.jpg',
 '/content/SiblingsDB/DBs/HQfp/192/_DSC0801.jpg',
 '/content/SiblingsDB/DBs/HQfp/209/_DSC0903.jpg',
 '/content/SiblingsDB/DBs/HQfp/209/_DSC0898.jpg',
 '/content/SiblingsDB/DBs/HQfp/211/_DSC2170.jpg',
 '/content/SiblingsDB/DBs/HQfp/211/_DSC2174.jpg',
 '/content/SiblingsDB/DBs/HQfp/146/_DSC0550.jpg',
 '/content/SiblingsDB/DBs/HQfp/146/_DSC0553.jpg',
 '/content/SiblingsDB/DBs/HQfp/42/_DSC5933.jpg',
 '/content/SiblingsDB/DBs/HQfp/42/_DSC5928.jpg',
 '/content/SiblingsDB/DBs/HQfp/177/_DSC0707.jpg',
 '/content/SiblingsDB/DBs/HQfp/177/_DSC0710.jpg',
 '/content/SiblingsDB/DBs/HQfp/207/_DSC0885.jpg',
 '/content/SiblingsDB/DBs/HQfp/207/_DSC0882.jpg',
 '/content/SiblingsDB/DBs/HQfp/96/_DSC0127.jpg',
 '/content/SiblingsDB/DBs/HQfp/96/_DSC0121.jpg',
 '/content/SiblingsDB/DBs/HQfp/150/_DSC0572.jpg',
 '/content/SiblingsDB/DBs/HQfp/150/_DSC0576.jpg',
 '/content/SiblingsDB/DBs/HQfp/143/_DSC0531.jpg',
 '/content/SiblingsDB/DBs/HQfp/143/_DSC0527.jpg',
 '/content/SiblingsDB/DBs/HQfp/13/_DSC5818.jpg',
 '/content/SiblingsDB/DBs/HQfp/13/_DSC5822.jpg',
 '/content/SiblingsDB/DBs/HQfp/183/_DSC0729.jpg',
 '/content/SiblingsDB/DBs/HQfp/183/_DSC0732.jpg',
 '/content/SiblingsDB/DBs/HQfp/53/_DSC5983.jpg',
 '/content/SiblingsDB/DBs/HQfp/53/_DSC5989.jpg',
 '/content/SiblingsDB/DBs/HQfp/240/_DSC2946.jpg',
 '/content/SiblingsDB/DBs/HQfp/240/_DSC2952.jpg',
 '/content/SiblingsDB/DBs/HQfp/43/_DSC5946.jpg',
 '/content/SiblingsDB/DBs/HQfp/43/_DSC5942.jpg',
 '/content/SiblingsDB/DBs/HQfp/237/_DSC2922.jpg',
 '/content/SiblingsDB/DBs/HQfp/237/_DSC2926.jpg',
 '/content/SiblingsDB/DBs/HQfp/119/_DSC0284.jpg',
 '/content/SiblingsDB/DBs/HQfp/119/_DSC0289.jpg',
 '/content/SiblingsDB/DBs/HQfp/166/_DSC0657.jpg',
 '/content/SiblingsDB/DBs/HQfp/166/_DSC0661.jpg',
 '/content/SiblingsDB/DBs/HQfp/144/_DSC0538.jpg',
 '/content/SiblingsDB/DBs/HQfp/144/_DSC0534.jpg',
 '/content/SiblingsDB/DBs/HQfp/212/_DSC2180.jpg',
 '/content/SiblingsDB/DBs/HQfp/212/_DSC2175.jpg',
 '/content/SiblingsDB/DBs/HQfp/224/_DSC2281.jpg',
 '/content/SiblingsDB/DBs/HQfp/224/_DSC2285.jpg',
 '/content/SiblingsDB/DBs/HQfp/44/_DSC5952.jpg',
 '/content/SiblingsDB/DBs/HQfp/44/_DSC5948.jpg',
 '/content/SiblingsDB/DBs/HQfp/94/_DSC0118.jpg',
 '/content/SiblingsDB/DBs/HQfp/94/_DSC0114.jpg',
 '/content/SiblingsDB/DBs/HQfp/128/_DSC0362.jpg',
 '/content/SiblingsDB/DBs/HQfp/128/_DSC0365.jpg',
 '/content/SiblingsDB/DBs/HQfp/193/_DSC0806.jpg',
 '/content/SiblingsDB/DBs/HQfp/193/_DSC0809.jpg',
 '/content/SiblingsDB/DBs/HQfp/35/_DSC5898.jpg',
 '/content/SiblingsDB/DBs/HQfp/35/_DSC5896.jpg',

In [ ]:
from tqdm import tqdm


face_dict = {}
for path in tqdm(paths):
  image = cv2.imread(path)
  faces = app.get(image)
  file_name = '/'.join(path.split('/')[2:])
  if len(faces) > 0:
    face_dict[file_name] = faces[0]
  else:
    face_dict[file_name] = None

  0%|          | 0/1157 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|██████████| 1157/1157 [23:32<00:00,  1.22s/it]

In [ ]:
[k for  k, v in face_dict.items() if v is None]

['SiblingsDB/DBs/HQf/160/160.jpg',
 'SiblingsDB/DBs/LQf/clooney_george.jpg',
 'SiblingsDB/DBs/LQf/brito_stephanie.jpg',
 'SiblingsDB/DBs/LQf/canseco_ozzie.jpg',
 'SiblingsDB/DBs/LQf/brito_kayky.jpg',
 'SiblingsDB/DBs/LQf/ribisi_giovanni.jpg',
 'SiblingsDB/DBs/LQf/diesel_vin.jpg',
 'SiblingsDB/DBs/LQf/bundchen_giselle.jpg',
 'SiblingsDB/DBs/LQf/bundchen_patricia.jpg',
 'SiblingsDB/DBs/LQf/diesel_paul.jpg',
 'SiblingsDB/DBs/LQf/oliveira_nenem.jpg',
 'SiblingsDB/DBs/LQf/canseco_jose.jpg',
 'SiblingsDB/DBs/LQf/silva2_rafael.jpg',
 'SiblingsDB/DBs/LQf/reeves_kim.jpg']

In [ ]:
list(face_dict.values())[0].keys()

dict_keys(['bbox', 'kps', 'det_score', 'landmark_3d_68', 'pose', 'landmark_2d_106', 'gender', 'age', 'embedding'])

In [ ]:
faces_info = {}
for k, v in face_dict.items():
  if v is not None:
    faces_info[k] = {
        "embedding": v["embedding"],
        "det_score": v["det_score"]
    }
  else:
    faces_info[k] = None

In [ ]:
from pickle import dump


with open('SiblingsDB_faces_info.pkl', 'wb') as f:
  dump(faces_info, f)

In [17]:
app = FaceAnalysis(name="buffalo_sc")
app.prepare(ctx_id=0, det_size=(640,640))

download_path: /root/.insightface/models/buffalo_sc
Downloading /root/.insightface/models/buffalo_sc.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_sc.zip...

100%|██████████| 14619/14619 [00:00<00:00, 49220.85KB/s]

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_sc/det_500m.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_sc/w600k_mbf.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)

In [21]:
face_dict = {}
for path in tqdm(paths):
  image = cv2.imread(path)
  faces = app.get(image)
  file_name = '/'.join(path.split('/')[2:])
  if len(faces) > 0:
    face_dict[file_name] = faces[0]
  else:
    face_dict[file_name] = None

100%|██████████| 1157/1157 [05:09<00:00,  3.74it/s]

In [23]:
faces_info = {}
for k, v in face_dict.items():
  if v is not None:
    faces_info[k] = {
        "embedding": v["embedding"],
        "det_score": v["det_score"]
    }
  else:
    faces_info[k] = None

In [24]:
from pickle import dump


with open('SiblingsDB_buffalo_sc_faces_info.pkl', 'wb') as f:
  dump(faces_info, f)